import { describe, expect, it } from "vitest";
import { creaturesData } from "./creatureData";
import { effectsCatalog } from "./data";
import { normalizeAbilityName } from "./runtimeHelpers";

// Regression guard for the "phantom ability" class of bug.
//
// The s1/s2/a1 status override snapshots and the v2 effects catalog are NOT
// regenerated by the wiki sync (only creatures.runtime.json is). When a
// creature's kit changes - e.g. Zeoarex losing "Poison Attack" when it was
// reworked into a Radiation carrier - any status entry sourced from the removed
// ability must NOT survive in `effectsCatalog`, or the engine keeps applying a
// phantom ailment (the observed bug: Zeoarex still poisoned opponents off an
// ability it no longer has). `data.ts` prunes entries whose `sourceAbility` is
// not a current ability; these tests pin that invariant.

function abilityNameKeys(creature: (typeof creaturesData)[number]): Set<string> {
  const keys = new Set<string>();
  for (const ability of [
    ...(creature.passiveAbilities ?? []),
    ...(creature.activatedAbilities ?? []),
    ...(creature.breathAbilities ?? []),
  ]) {
    keys.add(normalizeAbilityName(ability.name));
  }
  return keys;
}

describe("effectsCatalog prunes phantom abilities", () => {
  it("Zeoarex has no Poison Attack on-hit (reworked into a Radiation carrier)", () => {
    const eff = effectsCatalog["Zeoarex"] ?? {};
    const poison = (eff.applyStatusOnHit ?? []).filter((e) => e.statusId === "Poison_Status");
    expect(poison).toEqual([]);
    // Sanity: it still carries the abilities it actually has.
    const sources = (eff.applyStatusOnHitTaken ?? []).map((e) => e.sourceAbility);
    expect(sources).toContain("Defensive Corrosion");
  });

  it("no creature's status entries reference an ability it no longer has", () => {
    const offenders: string[] = [];
    for (const creature of creaturesData) {
      const keys = abilityNameKeys(creature);
      const eff = effectsCatalog[creature.name] ?? {};
      const lists: Array<[string, Array<{ sourceAbility?: string | null }>]> = [
        ["applyStatusOnHit", eff.applyStatusOnHit ?? []],
        ["applyStatusOnHitTaken", eff.applyStatusOnHitTaken ?? []],
        ["resistStatus", eff.resistStatus ?? []],
      ];
      for (const [kind, list] of lists) {
        for (const entry of list) {
          if (!entry.sourceAbility) continue;
          if (!keys.has(normalizeAbilityName(entry.sourceAbility))) {
            offenders.push(`${creature.name}/${kind}/${entry.sourceAbility}`);
          }
        }
      }
    }
    expect(offenders).toEqual([]);
  });
});
