import { describe, expect, it } from "vitest";

import { createExtendedDamageRuntime } from "./extendedDamageRuntime";
import type { CombatantRuntime, CombatantState } from "./runtimeContext";
import type { FinalStats } from "./types";
import { sanitizeAbilityTimingOverrides } from "./abilityTimingOverrides";

function minimalFinalStats(overrides: Partial<FinalStats> = {}): FinalStats {
  return {
    name: "Test",
    tier: 1,
    health: 1000,
    weight: 100,
    damage: 100,
    biteCooldown: 1,
    healthRegen: 0,
    stamina: 0,
    stamRegen: 0,
    walkAndSwimSpeed: 0,
    sprintSpeed: 0,
    turn: 0,
    venerationRate: 0,
    diet: "none",
    type: "test",
    mobilityOverride: "none",
    breath: "Test Breath",
    hasBreath: true,
    breathType: "Test Breath",
    approxNotes: [],
    appliedTraits: [],
    ...overrides,
  };
}

function minimalState(overrides: Partial<CombatantState> = {}): CombatantState {
  const state = {
    sideLabel: "A",
    compareSecondaryAttackOnly: false,
    comparePowerChargeEnabled: false,
    comparePowerChargeConsumed: false,
    compareGoreChargeEnabled: false,
    compareGoreChargeConsumed: false,
    compareHungerRuleEnabled: false,
    compareGourmandizerEnabled: false,
    compareDefiledGroundLevel: 0,
    compareDefiledGroundWeaknessEnabled: false,
    compareTrapsEnabled: false,
    compareTrailsEnabled: false,
    trailsFacetankOverrideActive: false,
    trailsFacetankOverridePrev: null,
    damageTrailNextTickAt: null,
    compareStartingHunger: 100,
    compareAppetiteBase: 100,
    compareHunger: 100,
    abilityPolicyOverrides: sanitizeAbilityTimingOverrides(undefined),
    hp: 1000,
    nextHitAt: Number.POSITIVE_INFINITY,
    statuses: {},
    channelingNextPulseAt: null,
    selfDestructArmedAt: null,
    selfDestructUsed: false,
    damageDealt: 100,
    dotDamageDealt: 0,
    dotDamageByStatus: {},
    dotDamageTakenByStatus: {},
    lifeLeechHealed: 0,
    lifeLeechActiveUntil: 0,
    lifeLeechCooldownUntil: 0,
    lifeLeechPlannedAt: 0,
    huntersCursePlannedAt: 0,
    unbridledRagePlannedAt: 0,
    nextRegenAt: Number.POSITIVE_INFINITY,
    regenBufferedTick: false,
    lastUpdateAt: 4.2,
    wardenRageOn: false,
    wardenRageStacks: 0,
    wardenRageCooldownUntil: 0,
    wardenRageTapUntil: 0,
    wardenRageHoldMode: false,
    hunkerOn: false,
    hunkerEffectStartsAt: Number.POSITIVE_INFINITY,
    hunkerDecisionKey: null,
    hunkerDecisionOn: null,
    hunkerLastDecisionAt: Number.NEGATIVE_INFINITY,
    reflectActiveUntil: null,
    reflectCooldownUntil: 0,
    totemActiveUntil: null,
    totemNextTickAt: null,
    cursedSigilCooldownUntil: 0,
    radiationNextTickAt: null,
    adrenalineActiveUntil: 0,
    adrenalineCooldownUntil: 0,
    hardenActiveUntil: 0,
    hardenCooldownUntil: 0,
    spiteCooldownUntil: 0,
    thornTrapCooldownUntil: 0,
    grimLariatCooldownUntil: 0,
    huntersCurseActiveUntil: 0,
    huntersCurseCooldownUntil: 0,
    unbridledRageActiveUntil: 0,
    unbridledRageCooldownUntil: 0,
    fortifyCooldownUntil: 0,
    fortifyImmuneUntil: 0,
    fortifyWeightBonusUntil: 0,
    lanceCooldownUntil: 0,
    lanceArmedUntil: 0,
    lanceAuraUntil: 0,
    lanceAuraNextTickAt: null,
    frostNovaCooldownUntil: 0,
    spiteChargeReadyAt: 0,
    spiteArmed: false,
    causeFearCooldownUntil: 0,
    refluxCooldownUntil: 0,
    refluxChargeReadyAt: 0,
    refluxArmed: false,
    refluxPuddleUntil: 0,
    refluxNextTickAt: null,
    rewindCooldownUntil: 0,
    rewindHistory: [],
    lastMeleeHitAt: 0,
    lastMeleeHitDamage: 0,
    shadowBarrageCooldownUntil: 0,
    shadowBarrageNextHitAt: null,
    shadowBarrageRemainingHits: 0,
    shadowBarrageBaseDamage: 0,
    frostSnareCooldownUntil: 0,
    poisonAreaCooldownUntil: 0,
    yolkBombCooldownUntil: 0,
    divinationCooldownUntil: 0,
    divinationChargesLeft: 0,
    toxicTrapCooldownUntil: 0,
    toxicTrapBitesRemaining: 0,
    toxicTrapNextTickAt: null,
    healingStepNextTickAt: 0,
    breathCapacityLeft: 10,
    breathRegenCooldown: 0,
    breathLastTickAt: 4,
    breathChainStacks: 0,
    breathAutoFireDelayUntil: null,
    breathCooldownUntil: 0,
    regenTicks: 0,
    regenHealed: 0,
    wardenRageEvents: [],
    abilityTimingEvents: [],
    plushieOffensiveStacksApplied: 0,
    plushieDefensiveStacksApplied: 0,
    biteCount: 0,
    breathTickCount: 0,
    statusStacksApplied: {},
    statusStacksBlocked: {},
    statusBlockFractions: {},
    abilityAppliedCounts: {},
    combatLog: [],
    badOmenOutcome: null,
    approxNotes: [],
    ...overrides,
  } as CombatantState;
  return state;
}

describe("extendedDamageRuntime", () => {
  it("keeps breath continuation on the next heartbeat after fights ending past the first second", () => {
    const runtime = createExtendedDamageRuntime({
      breathTickSec: 1,
      createCombatantState: (finalStats) => minimalState({ hp: finalStats.health, sideLabel: "B" }),
      nextEventAtSingle: (state, nextBreath) =>
        Number.isFinite(nextBreath) && nextBreath > state.lastUpdateAt ? nextBreath : Number.POSITIVE_INFINITY,
      updateStateAt: ({ time, attacker }) => {
        attacker.state.lastUpdateAt = time;
      },
      isActivesDisabledByNecro: () => false,
      handleMeleeHit: () => false,
      currentBiteCooldown: () => 1,
      handleDotTicks: () => {},
      handleChannelingPulse: () => {},
      handleSelfDestruct: () => {},
      handleTotemTick: () => {},
      applyBreathTick: ({ attacker, time }) => {
        attacker.state.damageDealt += 50;
        attacker.state.lastUpdateAt = time;
      },
    });

    const winnerRuntime = {
      creature: { name: "Winner", stats: minimalFinalStats() },
      effects: {},
      final: minimalFinalStats(),
      specialDefs: [],
      abilityValueByName: {},
      hasWardenRage: false,
      hasWardenResistance: false,
      hasReflect: false,
      hasTotem: false,
      hasDrowsyArea: false,
      hasLichMark: false,
      hasCursedSigil: false,
      hasAdrenaline: false,
      hasHealingStep: false,
      hasToxicTrail: false,
      hasPlagueTrail: false,
      hasFlameTrail: false,
      hasFrostTrail: false,
      hasSpite: false,
      hasCauseFear: false,
      hasReflux: false,
      hasRewind: false,
      hasShadowBarrage: false,
      hasFrostSnare: false,
      hasPoisonArea: false,
      hasYolkBomb: false,
      hasDivination: false,
      hasToxicTrap: false,
      hasHarden: false,
      hasHuntersCurse: false,
      hasUnbridledRage: false,
      hasFortify: false,
      lichMarkValue: null,
      yolkBombValue: null,
    } as CombatantRuntime;

    const loserRuntime = {
      creature: { name: "Loser", stats: minimalFinalStats({ hasBreath: false, breath: "N/A", breathType: null }) },
      effects: {},
      final: minimalFinalStats({ hasBreath: false, breath: "N/A", breathType: null }),
      specialDefs: [],
      abilityValueByName: {},
      hasWardenRage: false,
      hasWardenResistance: false,
      hasReflect: false,
      hasTotem: false,
      hasDrowsyArea: false,
      hasLichMark: false,
      hasCursedSigil: false,
      hasAdrenaline: false,
      hasHealingStep: false,
      hasToxicTrail: false,
      hasPlagueTrail: false,
      hasFlameTrail: false,
      hasFrostTrail: false,
      hasSpite: false,
      hasCauseFear: false,
      hasReflux: false,
      hasRewind: false,
      hasShadowBarrage: false,
      hasFrostSnare: false,
      hasPoisonArea: false,
      hasYolkBomb: false,
      hasDivination: false,
      hasToxicTrap: false,
      hasHarden: false,
      hasHuntersCurse: false,
      hasUnbridledRage: false,
      hasFortify: false,
      lichMarkValue: null,
      yolkBombValue: null,
    } as CombatantRuntime;

    const extended = runtime.computeExtendedDamagePotential(
      winnerRuntime,
      minimalState(),
      loserRuntime,
      { activesOn: false, breathOn: true, maxTimeSec: 90 },
    );

    expect(extended).toBeGreaterThan(0);
  });

  it("preserves defender combat special defs for projection instead of rebuilding a blank dummy from final stats only", () => {
    const runtime = createExtendedDamageRuntime({
      breathTickSec: 1,
      createCombatantState: (finalStats) => minimalState({ hp: finalStats.health, sideLabel: "B" }),
      nextEventAtSingle: (state) =>
        Number.isFinite(state.nextHitAt) && state.nextHitAt > state.lastUpdateAt ? state.nextHitAt : Number.POSITIVE_INFINITY,
      updateStateAt: ({ time, attacker }) => {
        attacker.state.lastUpdateAt = time;
      },
      isActivesDisabledByNecro: () => false,
      handleMeleeHit: ({ attacker, defender, time }) => {
        if (defender.runtime.specialDefs.length > 0 && defender.runtime.abilityValueByName.Guilt === 1.35) {
          attacker.state.damageDealt += 25;
        }
        attacker.state.lastUpdateAt = time;
        return true;
      },
      currentBiteCooldown: () => 1,
      handleDotTicks: () => {},
      handleChannelingPulse: () => {},
      handleSelfDestruct: () => {},
      handleTotemTick: () => {},
      applyBreathTick: () => {},
    });

    const winnerRuntime = {
      creature: { name: "Winner", stats: minimalFinalStats({ hasBreath: false, breath: "N/A", breathType: null }) },
      effects: {},
      final: minimalFinalStats({ hasBreath: false, breath: "N/A", breathType: null }),
      specialDefs: [],
      abilityValueByName: {},
      hasWardenRage: false,
      hasWardenResistance: false,
      hasReflect: false,
      hasTotem: false,
      hasDrowsyArea: false,
      hasLichMark: false,
      hasCursedSigil: false,
      hasAdrenaline: false,
      hasHealingStep: false,
      hasToxicTrail: false,
      hasPlagueTrail: false,
      hasFlameTrail: false,
      hasFrostTrail: false,
      hasSpite: false,
      hasCauseFear: false,
      hasReflux: false,
      hasRewind: false,
      hasShadowBarrage: false,
      hasFrostSnare: false,
      hasPoisonArea: false,
      hasYolkBomb: false,
      hasDivination: false,
      hasToxicTrap: false,
      hasHarden: false,
      hasHuntersCurse: false,
      hasUnbridledRage: false,
      hasFortify: false,
      lichMarkValue: null,
      yolkBombValue: null,
    } as CombatantRuntime;

    const loserRuntime = {
      creature: { name: "Loser", stats: minimalFinalStats({ hasBreath: false, breath: "N/A", breathType: null }) },
      effects: {},
      final: minimalFinalStats({ hasBreath: false, breath: "N/A", breathType: null }),
      specialDefs: [{ type: "damageTakenMultiplier", when: "onBeingBitten", multiplier: 1.35 }],
      abilityValueByName: { Guilt: 1.35 },
      hasWardenRage: false,
      hasWardenResistance: false,
      hasReflect: false,
      hasTotem: false,
      hasDrowsyArea: false,
      hasLichMark: false,
      hasCursedSigil: false,
      hasAdrenaline: false,
      hasHealingStep: false,
      hasToxicTrail: false,
      hasPlagueTrail: false,
      hasFlameTrail: false,
      hasFrostTrail: false,
      hasSpite: false,
      hasCauseFear: false,
      hasReflux: false,
      hasRewind: false,
      hasShadowBarrage: false,
      hasFrostSnare: false,
      hasPoisonArea: false,
      hasYolkBomb: false,
      hasDivination: false,
      hasToxicTrap: false,
      hasHarden: false,
      hasHuntersCurse: false,
      hasUnbridledRage: false,
      hasFortify: false,
      lichMarkValue: null,
      yolkBombValue: null,
    } as CombatantRuntime;

    const extended = runtime.computeExtendedDamagePotential(
      winnerRuntime,
      minimalState({ nextHitAt: 5.2 }),
      loserRuntime,
      { activesOn: false, breathOn: false, maxTimeSec: 90 },
    );

    expect(extended).toBeGreaterThan(0);
  });
});
