// AUTO-GENERATED by scripts/gen_spec_constants.ts - DO NOT EDIT BY HAND.
//
// Source of truth: the `specConstants` blocks in
// src/pages/referenceContent.ts. Regenerate with
// `npm run gen:spec-constants`. Tests read these instead of duplicating
// spec magnitudes.

export const SPEC_CONSTANTS = {
  /** status_acid_rain: "deals 3% max HP damage" */
  acid_rain_dot_pct_max_hp: 3,
  /** ability_adrenaline: "base cooldown is 90 seconds" */
  adrenaline_cooldown_sec: 90,
  /** ability_adrenaline: "Adrenaline lasts for 30 seconds" */
  adrenaline_duration_sec: 30,
  /** status_aftershock: "outgoing melee damage by 20%" */
  aftershock_outgoing_damage_reduction_pct: 20,
  /** status_aggressive: "Default duration is 10 seconds" */
  aggressive_duration_sec: 10,
  /** status_aggressive: "The emote grants 10 stacks" */
  aggressive_max_stacks: 10,
  /** status_aggressive: "by 25% multiplicatively while active" */
  aggressive_outgoing_damage_increase_pct: 25,
  /** compare_use_hunger_rules: "1 appetite unit every 36 seconds" */
  appetite_drain_sec_per_unit: 36,
  /** status_bad_omen: "reduces passive health regeneration by 25%" */
  bad_omen_regen_reduction_pct: 25,
  /** ability_berserk: "bite cooldown is multiplied by 0.5" */
  berserk_bite_cooldown_multiplier: 0.5,
  /** ability_berserk: "HP drops below 20%" */
  berserk_hp_gate_pct: 20,
  /** status_bleed: "2 flat damage per stack on each tick" */
  bleed_damage_per_stack_per_tick: 2,
  /** status_blessings_boon: "restores 3% max HP" */
  blessings_boon_heal_pct_max_hp: 3,
  /** status_burn: "0.025% max HP base" */
  burn_dot_base_pct_max_hp: 0.025,
  /** status_burn: "0.1% per remaining stack" */
  burn_dot_per_stack_pct_max_hp: 0.1,
  /** ability_cause_fear: "120 second cooldown" */
  cause_fear_cooldown_sec: 120,
  /** ability_cause_fear: "applies 10 stacks of Fear" */
  cause_fear_stacks: 10,
  /** status_corrosion: "deals 0.5% max HP damage" */
  corrosion_dot_pct_max_hp: 0.5,
  /** status_corrosion: "stops stacking at 90 stacks" */
  corrosion_max_stacks: 90,
  /** status_corrosion: "starts at 7.5%" */
  corrosion_weight_reduction_base_pct: 7.5,
  /** status_corrosion: "capped at 97.5%" */
  corrosion_weight_reduction_cap_pct: 97.5,
  /** status_corrosion: "increases by 1% per stack" */
  corrosion_weight_reduction_per_stack_pct: 1,
  /** ability_crystal_breath: "× 0.5 × 1.0 × (1 - breath resistance)" */
  crystal_breath_crit_multiplier: 1,
  /** ability_crystal_breath: "/ 100) × 0.5 × 1.0 ×" */
  crystal_breath_per_hit_multiplier: 0.5,
  /** ability_cursed_sigil: "85 second cooldown" */
  cursed_sigil_cooldown_sec: 85,
  /** status_disease: "reduces natural health regeneration by 25%" */
  disease_regen_reduction_pct: 25,
  /** ability_divination: "arms 3 bite charges" */
  divination_bite_charges: 3,
  /** ability_divination: "applies 2 stacks of Burn" */
  divination_burn_stacks: 2,
  /** ability_divination: "120 second cooldown" */
  divination_cooldown_sec: 120,
  /** ability_divination: "adds +50 flat damage" */
  divination_flat_damage: 50,
  /** ability_drowsy_area: "60 second cooldown" */
  drowsy_area_cooldown_sec: 60,
  /** ability_drowsy_area: "applies 5 stacks of Drowsy" */
  drowsy_area_stacks: 5,
  /** status_drowsy: "increases bite cooldown by 35%" */
  drowsy_bite_cooldown_increase_pct: 35,
  /** status_fear: "reduces outgoing melee damage by 45%" */
  fear_outgoing_damage_reduction_pct: 45,
  /** ability_fire_breath: "× 0.5 × 1.125 × (1 - breath resistance)" */
  fire_breath_crit_multiplier: 1.125,
  /** ability_fire_breath: "/ 100) × 0.5 × 1.125 ×" */
  fire_breath_per_hit_multiplier: 0.5,
  /** ability_first_strike: "at or above 75%" */
  first_strike_hp_gate_pct: 75,
  /** ability_fortify: "90 second cooldown" */
  fortify_cooldown_sec: 90,
  /** ability_frost_nova: "60 second cooldown" */
  frost_nova_cooldown_sec: 60,
  /** ability_frost_nova: "lasts for 15 seconds" */
  frost_nova_duration_sec: 15,
  /** ability_frost_nova: "applies 3 stacks of Frostbite" */
  frost_nova_frostbite_stacks: 3,
  /** ability_frost_snare: "205 second cooldown" */
  frost_snare_cooldown_sec: 205,
  /** ability_frost_snare: "applies 5 stacks of Frostbite" */
  frost_snare_frostbite_stacks: 5,
  /** status_frostbite: "increases bite cooldown by 2.5% per stack" */
  frostbite_bite_cooldown_increase_pct_per_stack: 2.5,
  /** ability_gold_breath: "× 0.25 × 1.0 × (1 - breath resistance)" */
  gold_breath_crit_multiplier: 1,
  /** ability_gold_breath: "/ 100) × 0.25 × 1.0 ×" */
  gold_breath_per_hit_multiplier: 0.25,
  /** compare_gore_charge: "applies 2 stacks of Bleed" */
  gore_charge_bleed_stacks: 2,
  /** compare_gore_charge: "9 stacks of Deep Wounds" */
  gore_charge_deep_wounds_stacks: 9,
  /** compare_use_hunger_rules: "overfilled meter 2x faster" */
  gourmandizer_overfill_drain_multiplier: 2,
  /** ability_green_fire_breath: "× 0.5 × 1.125 × (1 - breath resistance)" */
  green_fire_breath_crit_multiplier: 1.125,
  /** ability_green_fire_breath: "/ 100) × 0.5 × 1.125 ×" */
  green_fire_breath_per_hit_multiplier: 0.5,
  /** ability_grim_lariat: "60 second cooldown" */
  grim_lariat_cooldown_sec: 60,
  /** ability_grim_lariat: "50% of the user's current damage" */
  grim_lariat_damage_pct_user_damage: 50,
  /** ability_grim_lariat: "applies 8 stacks of Heartbroken" */
  grim_lariat_heartbroken_stacks: 8,
  /** status_guardians_seal: "reduces incoming damage by 85%" */
  guardian_seal_damage_reduction_pct: 85,
  /** status_guardians_seal: "seal holds at most 3 stacks" */
  guardian_seal_max_stacks: 3,
  /** ability_guardians_passage: "300 second cooldown" */
  guardians_passage_cooldown_sec: 300,
  /** ability_guardians_passage: "applies 3 stacks of Guardian's Seal" */
  guardians_passage_seal_stacks: 3,
  /** ability_guilt: "reduces incoming damage by 50%" */
  guilt_incoming_damage_reduction_pct: 50,
  /** ability_harden: "base cooldown is 120 seconds" */
  harden_cooldown_sec: 120,
  /** ability_harden: "lasts for 30 seconds" */
  harden_duration_sec: 30,
  /** ability_harden: "effective combat weight is multiplied by 1.35" */
  harden_weight_bonus_multiplier: 1.35,
  /** ability_haunt_breath: "× 0.75 × 1.175 × (1 - breath resistance)" */
  haunt_breath_crit_multiplier: 1.175,
  /** ability_haunt_breath: "/ 100) × 0.75 × 1.175 ×" */
  haunt_breath_per_hit_multiplier: 0.75,
  /** status_healing_ailment: "restores 7% of the target's max HP" */
  healing_ailment_heal_pct_max_hp: 7,
  /** status_healing_ailment: "every 15 seconds" */
  healing_ailment_tick_sec: 15,
  /** compare_healing_pulse: "every 90 seconds of cooldown" */
  healing_pulse_cooldown_sec: 90,
  /** status_heat_wave: "deals 1% max HP damage" */
  heat_wave_dot_pct_max_hp: 1,
  /** ability_heliolyths_judgement: "1.6% of the target's max HP" */
  heliolyths_judgement_pct_max_hp: 1.6,
  /** ability_hunters_curse: "melee damage is multiplied by 2" */
  hunters_curse_bite_multiplier: 2,
  /** ability_hunters_curse: "120 second cooldown" */
  hunters_curse_cooldown_sec: 120,
  /** ability_hunters_curse: "lasts for 30 seconds" */
  hunters_curse_duration_sec: 30,
  /** ability_hunters_curse: "loses 50% of its max HP" */
  hunters_curse_hp_cost_pct: 50,
  /** status_hypothermia: "deals 0.75% max HP damage" */
  hypothermia_dot_pct_max_hp: 0.75,
  /** ability_ice_breath: "× 0.5 × 1.0 × (1 - breath resistance)" */
  ice_breath_crit_multiplier: 1,
  /** ability_ice_breath: "/ 100) × 0.5 × 1.0 ×" */
  ice_breath_per_hit_multiplier: 0.5,
  /** ability_lance: "60 second cooldown" */
  lance_cooldown_sec: 60,
  /** ability_lance: "impact hit for 5% of the target's max HP" */
  lance_primary_pct_max_hp: 5,
  /** ability_lance: "deals 1% of the target's max HP" */
  lance_secondary_pct_max_hp: 1,
  /** ability_lich_mark: "30 second cooldown" */
  lich_mark_cooldown_sec: 30,
  /** ability_life_leech: "lasts for 12 seconds" */
  life_leech_duration_sec: 12,
  /** ability_lightning_breath: "× 1.5 × 1.25 × chain multiplier ×" */
  lightning_breath_crit_multiplier: 1.25,
  /** ability_lightning_breath: "/ 100) × 1.5 × 1.25 ×" */
  lightning_breath_per_hit_multiplier: 1.5,
  /** status_malices_mark: "reduces outgoing melee damage by 15%" */
  malices_mark_outgoing_damage_reduction_pct: 15,
  /** ability_miasma_breath: "× 0.25 × 1.125 × (1 - breath resistance)" */
  miasma_breath_crit_multiplier: 1.125,
  /** ability_miasma_breath: "/ 100) × 0.25 × 1.125 ×" */
  miasma_breath_per_hit_multiplier: 0.25,
  /** status_natural_regeneration: "ticks every 15 seconds" */
  natural_regen_interval_sec: 15,
  /** ability_plague_breath: "× 0.25 × 1.125 × (1 - breath resistance)" */
  plague_breath_crit_multiplier: 1.125,
  /** ability_plague_breath: "/ 100) × 0.25 × 1.125 ×" */
  plague_breath_per_hit_multiplier: 0.25,
  /** ability_plague_trail: "applies 2 stacks of Disease" */
  plague_trail_disease_stacks: 2,
  /** ability_plasma_beam: "× 0.5 × 1.175 × (1 - breath resistance)" */
  plasma_beam_crit_multiplier: 1.175,
  /** ability_plasma_beam: "/ 100) × 2.0 × 0.5 × 1.175 ×" */
  plasma_beam_per_hit_multiplier: 2,
  /** compare_poison_area: "15 second cooldown" */
  poison_area_cooldown_sec: 15,
  /** compare_poison_area: "applies 5 stacks of Poison" */
  poison_area_stacks: 5,
  /** status_poison: "starts at 0.2% max HP" */
  poison_dot_base_pct_max_hp: 0.2,
  /** status_poison: "increases by 0.05% per stack" */
  poison_dot_per_stack_pct_max_hp: 0.05,
  /** compare_power_charge: "gains +50% damage" */
  power_charge_first_hit_damage_pct: 50,
  /** compare_power_charge: "applies 2 stacks of Shredded Wings" */
  power_charge_shredded_wings_stacks: 2,
  /** ability_quick_recovery: "below 40% HP" */
  quick_recovery_hp_gate_pct: 40,
  /** ability_quick_recovery: "2x at 0% HP" */
  quick_recovery_max_multiplier: 2,
  /** status_radiation: "0.5% max HP damage per tick" */
  radiation_dot_pct_max_hp: 0.5,
  /** ability_reflect: "45 second cooldown" */
  reflect_cooldown_sec: 45,
  /** ability_reflect: "lasts for 6 seconds" */
  reflect_duration_sec: 6,
  /** ability_reflux: "120 second cooldown" */
  reflux_cooldown_sec: 120,
  /** ability_reflux: "5% of the target's max HP" */
  reflux_primary_pct_max_hp: 5,
  /** ability_reflux: "deals direct damage equal to 1.5% of the target's max HP" */
  reflux_secondary_pct_max_hp: 1.5,
  /** ability_rewind: "100 second cooldown" */
  rewind_cooldown_sec: 100,
  /** ability_rewind: "capped at 25% of the user's max HP" */
  rewind_heal_cap_pct_max_hp: 25,
  /** ability_rock_breath: "× 1.0 × 1.05 × (1 - breath resistance)" */
  rock_breath_crit_multiplier: 1.05,
  /** ability_rock_breath: "/ 100) × 1.0 × 1.05 ×" */
  rock_breath_per_hit_multiplier: 1,
  /** ability_sand_breath: "× 0.25 × 1.0 × (1 - breath resistance)" */
  sand_breath_crit_multiplier: 1,
  /** ability_sand_breath: "/ 100) × 0.25 × 1.0 ×" */
  sand_breath_per_hit_multiplier: 0.25,
  /** status_scared: "Default duration is 10 seconds" */
  scared_duration_sec: 10,
  /** status_scared: "The emote grants 10 stacks" */
  scared_max_stacks: 10,
  /** status_scared: "reduces outgoing melee damage by 50%" */
  scared_outgoing_damage_reduction_pct: 50,
  /** ability_self_destruct: "capped down to 15% of max HP" */
  self_destruct_cap_pct: 15,
  /** ability_self_destruct: "300 second cooldown" */
  self_destruct_cooldown_sec: 300,
  /** ability_self_destruct: "deals 10% of the target's max HP" */
  self_destruct_damage_pct_max_hp: 10,
  /** ability_shadow_barrage: "30 second cooldown" */
  shadow_barrage_cooldown_sec: 30,
  /** status_sickly: "reduces passive health regen by 20%" */
  sickly_regen_reduction_pct: 20,
  /** ability_solar_beam: "× 1.5 × 1.0 × (1 - breath resistance)" */
  solar_beam_crit_multiplier: 1,
  /** ability_solar_beam: "/ 100) × 1.5 × 1.0 ×" */
  solar_beam_per_hit_multiplier: 1.5,
  /** ability_spirit_glare: "× 1.0 × 1.0 × (1 - breath resistance)" */
  spirit_glare_crit_multiplier: 1,
  /** ability_spirit_glare: "/ 100) × 1.0 × 1.0 ×" */
  spirit_glare_per_hit_multiplier: 1,
  /** ability_spite: "20 second cooldown" */
  spite_cooldown_sec: 20,
  /** compare_use_hunger_rules: "0.5% of max health per stack" */
  starving_damage_pct_max_hp: 0.5,
  /** status_sticky_teeth: "increases bite cooldown by 65%" */
  sticky_teeth_bite_cooldown_increase_pct: 65,
  /** ability_storm_breath: "× 0.01 × 1.0 × (1 - breath resistance)" */
  storm_breath_crit_multiplier: 1,
  /** ability_storm_breath: "/ 100) × 0.01 × 1.0 ×" */
  storm_breath_per_hit_multiplier: 0.01,
  /** compare_storming: "takes 10% more damage" */
  storming_incoming_damage_increase_pct: 10,
  /** ability_thorn_trap: "applies 6 stacks of Bleed" */
  thorn_trap_bleed_stacks: 6,
  /** ability_thorn_trap: "35 second cooldown" */
  thorn_trap_cooldown_sec: 35,
  /** ability_thorn_trap: "5% of the target's max HP" */
  thorn_trap_damage_pct_max_hp: 5,
  /** ability_thorn_trap: "applies 2 stacks of Freeze" */
  thorn_trap_freeze_stacks: 2,
  /** ability_totem: "active for 30 seconds" */
  totem_active_window_sec: 30,
  /** ability_totem: "180 second cooldown" */
  totem_cooldown_sec: 180,
  /** ability_toxic_trail: "applies 2 stacks of Poison" */
  toxic_trail_poison_stacks: 2,
  /** ability_toxic_trap: "75 second cooldown" */
  toxic_trap_cooldown_sec: 75,
  /** ability_toxic_trap: "always exactly 25 opponent bites" */
  toxic_trap_durability_bites: 25,
  /** ability_toxic_trap: "receives 5 stacks of Poison" */
  toxic_trap_poison_stacks: 5,
  /** ability_toxin_breath: "× 0.25 × 1.025 × (1 - breath resistance)" */
  toxin_breath_crit_multiplier: 1.025,
  /** ability_toxin_breath: "/ 100) × 0.25 × 1.025 ×" */
  toxin_breath_per_hit_multiplier: 0.25,
  /** ability_two_faced: "Madness multiplies damage by 0.625" */
  two_faced_madness_multiplier: 0.625,
  /** ability_two_faced: "Tranquility multiplies damage by 1.6" */
  two_faced_tranquility_multiplier: 1.6,
  /** ability_unbridled_rage: "120 second cooldown" */
  unbridled_rage_cooldown_sec: 120,
  /** ability_unbridled_rage: "lasts for 30 seconds" */
  unbridled_rage_duration_sec: 30,
  /** ability_virus_breath: "× 0.25 × 1.0 × (1 - breath resistance)" */
  virus_breath_crit_multiplier: 1,
  /** ability_virus_breath: "/ 100) × 0.25 × 1.0 ×" */
  virus_breath_per_hit_multiplier: 0.25,
  /** ability_wardens_rage: "reaches 8.5x damage at full strength" */
  wardens_rage_cap_multiplier: 8.5,
  /** ability_wardens_resistance: "HP is at or below 50%" */
  wardens_resistance_hp_gate_pct: 50,
  /** ability_water_breath: "× 0.75 × 1.1 × (1 - breath resistance)" */
  water_breath_crit_multiplier: 1.1,
  /** ability_water_breath: "/ 100) × 0.75 × 1.1 ×" */
  water_breath_per_hit_multiplier: 0.75,
  /** ability_yolk_bomb: "30 second cooldown" */
  yolk_bomb_cooldown_sec: 30,
} as const;
