// Generated by `UPDATE_CONTRACT_MANIFEST=1 cargo test --lib contract_manifest`.
// Do not edit by hand.
//
// FNV-1a over the serde field names of the two input contracts that cross
// the WASM boundary. `rustMatchupLoader` compares it against the digest the
// loaded binary reports; both come from `contract_manifest::schema_hash`, so
// they disagree exactly when the committed `.wasm` predates a contract change.
export const CONTRACT_SCHEMA_HASH = "faca8c5e9a0f350b";
