import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import { applyRulesAndBuild } from "../engine";
import { creatureByName } from "../engine/creatureData";
import { __test_toRustStatusMeleeStats } from "./rustBestBuildsRuntime";

// Stat-side class-1b threading-drop guard, mirroring the config-side
// "ComposableAbilityConfig producer coverage" in buildAbilityConfig.test.ts.
// schemaSeamParity.test.ts proves the TS mirror TYPE lists every Rust stat
// field; this proves some PRODUCER (`toRustStatusMeleeStats`) actually SETS each
// one - a field present in the mirror but set by no producer is dropped by
// stripNullsForWasm and silently inert in the Rust-only Compare. The oracle is
// wasm-engine/contract_manifest.json (generated by contract_manifest.rs).
describe("SimpleCombatantStats producer coverage", () => {
  // Per-fight fields the Compare/BestBuilds runtime layer appends AFTER the
  // shared stat producer (`rustCompareMatchupRuntime.ts` ~208-215 wraps
  // `toRustStatusMeleeStats` and adds these from the per-fight inputs), so they
  // are legitimately absent from the shared producer's output - analogous to
  // the config guard's COMPARE_RUNTIME_ONLY_KEYS. A new SHARED stat field that
  // no producer sets still trips `missing`.
  const RUNTIME_LAYER_FIELDS = new Set<string>([
    "startingStatuses",
    "disabledAbilities",
    "compareAirRuleCooldownSec",
    "aerialDodgeHitChancePct",
  ]);

  it("every Rust SimpleCombatantStats field is set by some producer (no threading-drop)", () => {
    const manifestPath = path.resolve(
      path.dirname(fileURLToPath(import.meta.url)),
      "../../wasm-engine/contract_manifest.json",
    );
    const manifestStats: string[] = JSON.parse(
      readFileSync(manifestPath, "utf8"),
    ).simpleCombatantStats;

    // The stat path is a flat object literal (not a conditional builder), so one
    // call emits nearly every key; union a few creatures x plushie sets as
    // belt-and-suspenders against the optional map-shaped fields.
    const produced = new Set<string>();
    for (const name of Object.keys(creatureByName).slice(0, 6)) {
      for (const plushies of [[] as string[], ["Cat"], ["Tannenbaum"]]) {
        const runtime = creatureByName[name];
        const finalStats = applyRulesAndBuild(runtime, {
          venerationStage: 5,
          traits: ["Damage", "Bite"],
          ascensionAssignments: ["Damage", "Damage", "Damage", "Damage", "Damage"],
          plushies,
        });
        for (const k of Object.keys(__test_toRustStatusMeleeStats(runtime, finalStats))) {
          produced.add(k);
        }
      }
    }

    const allowed = new Set<string>([...produced, ...RUNTIME_LAYER_FIELDS]);
    const missing = manifestStats.filter((k) => !allowed.has(k));
    expect(
      missing,
      "Rust SimpleCombatantStats fields no TS producer sets - thread them in " +
        "toRustStatusMeleeStats (or, if added by the runtime layer, RUNTIME_LAYER_FIELDS)",
    ).toEqual([]);

    const extra = [...produced].filter((k) => !manifestStats.includes(k));
    expect(
      extra,
      "producer keys with no matching Rust stat field (stale mirror entry)",
    ).toEqual([]);
  });
});
