export const MODELED_OTHER_ABILITIES = [
  "Life Leech",
  "Wing Shredder",
  "Serrated Teeth",
  "Reflect",
  "Totem",
  "Drowsy Area",
  "Lich Mark",
  "Warden's Rage",
  "Warden's Resistance",
  "Two-Faced",
  "Hunker",
  "Harden",
  "Adrenaline",
  "Cursed Sigil",
  "Hunters Curse",
  "Unbridled Rage",
  "Thorn Trap",
  "Fortify",
  "Sticky Fur",
  "Aura (Disease)",
  "Aura (Corrosion)",
  "Aura (Burn)",
  "Self-Destruct",
  "Guilt",
  "Unbreakable",
  "Berserk",
  "First Strike",
  "Breath Resistance",
  "Spite",
  "Cause Fear",
  "Frost Snare",
  "Poison Area",
  "Yolk Bomb",
  "Divination",
  "Toxic Trap",
  "Rewind",
  "Shadow Barrage",
  "Lance",
  "Frost Nova",
  "Reflux",
  "Heal Breath",
  "Heal Beam",
  "Solar Beam",
  "Spirit Glare",
  "Cloud Breath",
  "Grim Lariat",
  "Ligament Tear",
  "Stubborn Stacker",
  "Toxic Trail",
  "Plague Trail",
  "Flame Trail",
  "Frost Trail",
  "Healing Step",
  "Cocoon",
  "Expunge",
] as const;
