//! Wire-contract field manifest.
//!
//! The single oracle of the serde field names that cross the WASM boundary for
//! the two hand-mirrored input contracts: [`SimpleCombatantStats`] and
//! [`ComposableAbilityConfig`]. The committed `contract_manifest.json` is read
//! by the TS-side parity test (`src/optimizer/schemaSeamParity.test.ts`), which
//! has no other way to learn the Rust field names - so a field added here but not
//! mirrored in `rustMatchupBridge.ts` (or not threaded from `FinalStats`) fails
//! that test instead of silently no-opping in the Rust-only Compare path.
//!
//! Both structs serialize every field - there is no `skip_serializing_if` on the
//! input contracts (only on the output `BestBuildsMatchupSummary`) - so the key
//! set is taken from `Default`. If a future field gains `skip_serializing_if` it
//! must be populated non-default below, or its key silently drops from the oracle
//! and goes unguarded.

use std::collections::BTreeMap;

use crate::composable::ComposableAbilityConfig;
use crate::contracts::SimpleCombatantStats;

#[cfg(test)]
const MANIFEST_PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/contract_manifest.json");
#[cfg(test)]
const GENERATED_HASH_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../src/optimizer/contractSchemaHash.generated.ts"
);

fn serialized_keys<T: serde::Serialize>(value: &T) -> Vec<String> {
    let json = serde_json::to_value(value).expect("contract serializes to JSON");
    let obj = json.as_object().expect("contract serializes to a JSON object");
    let mut keys: Vec<String> = obj.keys().cloned().collect();
    keys.sort();
    keys
}

/// The wire contract as one string, `name:key,key|name:key,key`. Only the serde
/// names and their grouping go in - nothing about types or declaration order -
/// so the digest moves when, and only when, the boundary moves.
fn canonical_contract() -> String {
    current_manifest()
        .iter()
        .map(|(name, keys)| format!("{name}:{}", keys.join(",")))
        .collect::<Vec<_>>()
        .join("|")
}

/// FNV-1a over [`canonical_contract`]. Exported through the bridge as the
/// contract version, and written into `contractSchemaHash.generated.ts` by the
/// test below so the TS side can tell a stale `.wasm` from a current one: both
/// come from this function, so they disagree exactly when the committed binary
/// predates a contract change.
pub fn schema_hash() -> String {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in canonical_contract().as_bytes() {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x1000_0000_01b3);
    }
    format!("{hash:016x}")
}

fn current_manifest() -> BTreeMap<String, Vec<String>> {
    let mut manifest = BTreeMap::new();
    manifest.insert(
        "simpleCombatantStats".to_string(),
        serialized_keys(&SimpleCombatantStats::default()),
    );
    manifest.insert(
        "composableAbilityConfig".to_string(),
        serialized_keys(&ComposableAbilityConfig::default()),
    );
    manifest
}

#[cfg(test)]
fn write_manifest(manifest: &BTreeMap<String, Vec<String>>) {
    let mut json = serde_json::to_string_pretty(manifest).expect("manifest serializes");
    json.push('\n');
    std::fs::write(MANIFEST_PATH, json).expect("write contract_manifest.json");
}

#[cfg(test)]
fn write_generated_hash(hash: &str) {
    let module = format!(
        "// Generated by `UPDATE_CONTRACT_MANIFEST=1 cargo test --lib contract_manifest`.\n\
         // Do not edit by hand.\n\
         //\n\
         // FNV-1a over the serde field names of the two input contracts that cross\n\
         // the WASM boundary. `rustMatchupLoader` compares it against the digest the\n\
         // loaded binary reports; both come from `contract_manifest::schema_hash`, so\n\
         // they disagree exactly when the committed `.wasm` predates a contract change.\n\
         export const CONTRACT_SCHEMA_HASH = \"{hash}\";\n"
    );
    std::fs::write(GENERATED_HASH_PATH, module).expect("write contractSchemaHash.generated.ts");
}

/// Regenerate with `UPDATE_CONTRACT_MANIFEST=1 cargo test --lib contract_manifest`.
/// Without the env var (the CI default) this is a pure verifier: a field added,
/// removed, or renamed on either input contract drifts the live key set away
/// from the committed manifest and fails here.
#[test]
fn contract_manifest_matches_committed() {
    let current = current_manifest();
    if std::env::var("UPDATE_CONTRACT_MANIFEST").is_ok() {
        write_manifest(&current);
        write_generated_hash(&schema_hash());
        return;
    }
    let committed_raw = std::fs::read_to_string(MANIFEST_PATH).unwrap_or_else(|_| {
        panic!(
            "contract_manifest.json missing — generate it with \
             UPDATE_CONTRACT_MANIFEST=1 cargo test --lib contract_manifest"
        )
    });
    let committed: BTreeMap<String, Vec<String>> =
        serde_json::from_str(&committed_raw).expect("contract_manifest.json parses as a name map");
    assert_eq!(
        current, committed,
        "wire-contract field set drifted from contract_manifest.json — a field was \
         added/removed/renamed on SimpleCombatantStats or ComposableAbilityConfig. \
         Regenerate: UPDATE_CONTRACT_MANIFEST=1 cargo test --lib contract_manifest, \
         then mirror the field in rustMatchupBridge.ts (schemaSeamParity.test.ts confirms)."
    );

    // The digest the TS loader compares against ships as a generated module, so
    // it has to be regenerated alongside the manifest. Left behind, it would
    // accuse every freshly built binary of being stale.
    let generated = std::fs::read_to_string(GENERATED_HASH_PATH).unwrap_or_else(|_| {
        panic!(
            "contractSchemaHash.generated.ts missing - generate it with \
             UPDATE_CONTRACT_MANIFEST=1 cargo test --lib contract_manifest"
        )
    });
    let expected = schema_hash();
    assert!(
        generated.contains(&format!("\"{expected}\"")),
        "contractSchemaHash.generated.ts carries a stale digest - the contract moved. \
         Regenerate: UPDATE_CONTRACT_MANIFEST=1 cargo test --lib contract_manifest"
    );
}
