//! AUTO-GENERATED by scripts/gen_effects_registry.ts - DO NOT EDIT BY HAND.
//!
//! Source of truth: src/engine/statusCatalog.ts NAME_TO_EFFECT_META.
//! Regenerate with `npm run gen:registry` after editing the catalog.
//!
//! Effects in this registry are the ones that have a Reference entry
//! plus a NAME_TO_EFFECT_META row. Engine-only statuses (e.g.
//! Aftershock, Ashy_Lungs, Paralyze_Status) intentionally return None
//! here - the legacy hand-written paths in statuses.rs cover them.

#![allow(dead_code)]

#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum Polarity {
    Positive,
    Negative,
    Neutral,
}

#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum Category {
    RegenBuff,
    StatBuff,
    StatDebuff,
    DotDamage,
    TickHeal,
    Control,
    AilmentMeta,
    NeutralMarker,
}

#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum StackRule {
    Stacking,
    NonStacking,
    Unique,
}

pub fn polarity(status_id: &str) -> Option<Polarity> {
    match status_id {
        "Acid_Rain_Status" => Some(Polarity::Negative),
        "Aftershock" => Some(Polarity::Negative),
        "Aggressive_Status" => Some(Polarity::Positive),
        "Aggressive_Bear_Status" => Some(Polarity::Positive),
        "Ashy_Lungs" => Some(Polarity::Negative),
        "Bad_Omen" => Some(Polarity::Negative),
        "Bleed_Status" => Some(Polarity::Negative),
        "Blessings_Boon" => Some(Polarity::Positive),
        "Blurred_Vision_Status" => Some(Polarity::Negative),
        "Broken_Bones_Status" => Some(Polarity::Negative),
        "Broken_Legs_Status" => Some(Polarity::Negative),
        "Burn_Status" => Some(Polarity::Negative),
        "Clean_Water_Status" => Some(Polarity::Positive),
        "Confusion_Status" => Some(Polarity::Negative),
        "Corrosion_Status" => Some(Polarity::Negative),
        "Deep_Wounds_Status" => Some(Polarity::Negative),
        "Disease_Status" => Some(Polarity::Negative),
        "Drowsy_Status" => Some(Polarity::Negative),
        "Fear_Status" => Some(Polarity::Negative),
        "Flowering_Status" => Some(Polarity::Positive),
        "Freeze_Status" => Some(Polarity::Negative),
        "Frostbite_Status" => Some(Polarity::Negative),
        "Water_Gale_Status" => Some(Polarity::Negative),
        "Healing_Ailment" => Some(Polarity::Positive),
        "Heartbroken_Status" => Some(Polarity::Negative),
        "Heat_Wave_Status" => Some(Polarity::Negative),
        "Hypothermia_Status" => Some(Polarity::Negative),
        "Injury_Status" => Some(Polarity::Negative),
        "Malices_Mark" => Some(Polarity::Negative),
        "Muddy_Status" => Some(Polarity::Positive),
        "Necropoison_Status" => Some(Polarity::Negative),
        "Paralyze_Status" => Some(Polarity::Negative),
        "Poison_Status" => Some(Polarity::Negative),
        "Radiation_Status" => Some(Polarity::Negative),
        "Refreshed_Status" => Some(Polarity::Positive),
        "Scared_Status" => Some(Polarity::Negative),
        "Scared_Bear_Status" => Some(Polarity::Negative),
        "Shock_Status" => Some(Polarity::Negative),
        "Shredded_Wings" => Some(Polarity::Negative),
        "Sickly_Status" => Some(Polarity::Negative),
        "Slow_Status" => Some(Polarity::Negative),
        "Sticky_Teeth_Status" => Some(Polarity::Negative),
        "Sticky_Trap_Status" => Some(Polarity::Negative),
        "Stolen_Speed_Status" => Some(Polarity::Negative),
        "Torn_Ligaments_Status" => Some(Polarity::Negative),
        "Water_Regeneration_Status" => Some(Polarity::Positive),
        _ => None,
    }
}

pub fn category(status_id: &str) -> Option<Category> {
    match status_id {
        "Acid_Rain_Status" => Some(Category::DotDamage),
        "Aftershock" => Some(Category::NeutralMarker),
        "Aggressive_Status" => Some(Category::StatBuff),
        "Aggressive_Bear_Status" => Some(Category::StatBuff),
        "Ashy_Lungs" => Some(Category::NeutralMarker),
        "Bad_Omen" => Some(Category::AilmentMeta),
        "Bleed_Status" => Some(Category::DotDamage),
        "Blessings_Boon" => Some(Category::TickHeal),
        "Blurred_Vision_Status" => Some(Category::NeutralMarker),
        "Broken_Bones_Status" => Some(Category::NeutralMarker),
        "Broken_Legs_Status" => Some(Category::NeutralMarker),
        "Burn_Status" => Some(Category::DotDamage),
        "Clean_Water_Status" => Some(Category::RegenBuff),
        "Confusion_Status" => Some(Category::Control),
        "Corrosion_Status" => Some(Category::DotDamage),
        "Deep_Wounds_Status" => Some(Category::StatDebuff),
        "Disease_Status" => Some(Category::StatDebuff),
        "Drowsy_Status" => Some(Category::Control),
        "Fear_Status" => Some(Category::Control),
        "Flowering_Status" => Some(Category::StatBuff),
        "Freeze_Status" => Some(Category::Control),
        "Frostbite_Status" => Some(Category::StatDebuff),
        "Water_Gale_Status" => Some(Category::Control),
        "Healing_Ailment" => Some(Category::StatBuff),
        "Heartbroken_Status" => Some(Category::StatDebuff),
        "Heat_Wave_Status" => Some(Category::DotDamage),
        "Hypothermia_Status" => Some(Category::DotDamage),
        "Injury_Status" => Some(Category::NeutralMarker),
        "Malices_Mark" => Some(Category::AilmentMeta),
        "Muddy_Status" => Some(Category::RegenBuff),
        "Necropoison_Status" => Some(Category::AilmentMeta),
        "Paralyze_Status" => Some(Category::Control),
        "Poison_Status" => Some(Category::DotDamage),
        "Radiation_Status" => Some(Category::NeutralMarker),
        "Refreshed_Status" => Some(Category::RegenBuff),
        "Scared_Status" => Some(Category::StatDebuff),
        "Scared_Bear_Status" => Some(Category::StatDebuff),
        "Shock_Status" => Some(Category::Control),
        "Shredded_Wings" => Some(Category::NeutralMarker),
        "Sickly_Status" => Some(Category::StatDebuff),
        "Slow_Status" => Some(Category::StatDebuff),
        "Sticky_Teeth_Status" => Some(Category::StatDebuff),
        "Sticky_Trap_Status" => Some(Category::Control),
        "Stolen_Speed_Status" => Some(Category::StatDebuff),
        "Torn_Ligaments_Status" => Some(Category::StatDebuff),
        "Water_Regeneration_Status" => Some(Category::TickHeal),
        _ => None,
    }
}

pub fn stack_rule(status_id: &str) -> Option<StackRule> {
    match status_id {
        "Acid_Rain_Status" => Some(StackRule::Stacking),
        "Aftershock" => Some(StackRule::Stacking),
        "Aggressive_Status" => Some(StackRule::NonStacking),
        "Aggressive_Bear_Status" => Some(StackRule::NonStacking),
        "Ashy_Lungs" => Some(StackRule::Stacking),
        "Bad_Omen" => Some(StackRule::Stacking),
        "Bleed_Status" => Some(StackRule::Stacking),
        "Blessings_Boon" => Some(StackRule::Stacking),
        "Blurred_Vision_Status" => Some(StackRule::Stacking),
        "Broken_Bones_Status" => Some(StackRule::Stacking),
        "Broken_Legs_Status" => Some(StackRule::Stacking),
        "Burn_Status" => Some(StackRule::Stacking),
        "Clean_Water_Status" => Some(StackRule::NonStacking),
        "Confusion_Status" => Some(StackRule::Stacking),
        "Corrosion_Status" => Some(StackRule::Stacking),
        "Deep_Wounds_Status" => Some(StackRule::Stacking),
        "Disease_Status" => Some(StackRule::Stacking),
        "Drowsy_Status" => Some(StackRule::Stacking),
        "Fear_Status" => Some(StackRule::Stacking),
        "Flowering_Status" => Some(StackRule::Stacking),
        "Freeze_Status" => Some(StackRule::Stacking),
        "Frostbite_Status" => Some(StackRule::Stacking),
        "Water_Gale_Status" => Some(StackRule::Stacking),
        "Healing_Ailment" => Some(StackRule::Stacking),
        "Heartbroken_Status" => Some(StackRule::Stacking),
        "Heat_Wave_Status" => Some(StackRule::Stacking),
        "Hypothermia_Status" => Some(StackRule::Stacking),
        "Injury_Status" => Some(StackRule::Stacking),
        "Malices_Mark" => Some(StackRule::Stacking),
        "Muddy_Status" => Some(StackRule::NonStacking),
        "Necropoison_Status" => Some(StackRule::Stacking),
        "Paralyze_Status" => Some(StackRule::Stacking),
        "Poison_Status" => Some(StackRule::Stacking),
        "Radiation_Status" => Some(StackRule::Stacking),
        "Refreshed_Status" => Some(StackRule::NonStacking),
        "Scared_Status" => Some(StackRule::NonStacking),
        "Scared_Bear_Status" => Some(StackRule::NonStacking),
        "Shock_Status" => Some(StackRule::Stacking),
        "Shredded_Wings" => Some(StackRule::Stacking),
        "Sickly_Status" => Some(StackRule::Stacking),
        "Slow_Status" => Some(StackRule::Stacking),
        "Sticky_Teeth_Status" => Some(StackRule::Stacking),
        "Sticky_Trap_Status" => Some(StackRule::Stacking),
        "Stolen_Speed_Status" => Some(StackRule::Stacking),
        "Torn_Ligaments_Status" => Some(StackRule::Stacking),
        "Water_Regeneration_Status" => Some(StackRule::Stacking),
        _ => None,
    }
}

pub fn default_duration_sec(status_id: &str) -> Option<f64> {
    match status_id {
        "Aggressive_Status" => Some(10.0_f64),
        "Aggressive_Bear_Status" => Some(10.0_f64),
        "Clean_Water_Status" => Some(180.0_f64),
        "Muddy_Status" => Some(90.0_f64),
        "Refreshed_Status" => Some(180.0_f64),
        "Scared_Status" => Some(10.0_f64),
        "Scared_Bear_Status" => Some(10.0_f64),
        _ => None,
    }
}

pub fn default_tick_sec(status_id: &str) -> Option<f64> {
    match status_id {
        "Acid_Rain_Status" => Some(3.0_f64),
        "Bleed_Status" => Some(3.0_f64),
        "Blessings_Boon" => Some(3.0_f64),
        "Burn_Status" => Some(3.0_f64),
        "Corrosion_Status" => Some(3.0_f64),
        "Heat_Wave_Status" => Some(3.0_f64),
        "Hypothermia_Status" => Some(3.0_f64),
        "Poison_Status" => Some(3.0_f64),
        "Water_Regeneration_Status" => Some(3.0_f64),
        _ => None,
    }
}

pub fn default_max_stacks(status_id: &str) -> Option<f64> {
    match status_id {
        "Sticky_Teeth_Status" => Some(10.0_f64),
        _ => None,
    }
}

pub fn regen_modifier_pct(status_id: &str) -> Option<f64> {
    match status_id {
        "Bad_Omen" => Some(-25.0_f64),
        "Bleed_Status" => Some(-100.0_f64),
        "Clean_Water_Status" => Some(20.0_f64),
        "Muddy_Status" => Some(25.0_f64),
        "Refreshed_Status" => Some(5.0_f64),
        "Sickly_Status" => Some(-20.0_f64),
        _ => None,
    }
}

pub fn regen_modifier_per_stack_pct(status_id: &str) -> Option<f64> {
    match status_id {
        "Burn_Status" => Some(-10.0_f64),
        "Disease_Status" => Some(-15.0_f64),
        _ => None,
    }
}

pub fn is_known(status_id: &str) -> bool {
    polarity(status_id).is_some()
}
