/// Fixture-based parity tests: composable engine must match TS-generated expected values.
///
/// Fixtures live in wasm-engine/fixtures/ and are generated by TS scripts.
/// When a test fails, check whether:
///   1. Rust has a bug (composable diverges from TS on this mechanic) - fix Rust
///   2. Fixture is stale (mechanic intentionally changed) - regenerate fixture from TS
///
/// Tolerance: winner must be exact; TTK / death time within FLOAT_TOL (0.05s).
#[cfg(test)]
#[allow(clippy::module_inception)] // established test-module name; renaming churns all use-paths for no gain
mod fixture_tests {
    use crate::composable::{simulate_composable_matchup, ComposableAbilityConfig};
    use crate::contracts::{
        BestBuildsMatchupSummary, SimpleCombatantStats, SimpleBreathProfile,
    };
    use crate::contracts::SimpleAbilityTimingMode;
    use serde::Deserialize;

    const FLOAT_TOL: f64 = 0.05;

    // ─── Fixture case types ──────────────────────────────────────────────────

    #[derive(Deserialize)]
    struct MeleeCase {
        name: String,
        attacker: SimpleCombatantStats,
        defender: SimpleCombatantStats,
        #[serde(rename = "maxTimeSec")]
        max_time_sec: f64,
        #[serde(rename = "expectedSummary")]
        expected: BestBuildsMatchupSummary,
    }

    #[derive(Deserialize)]
    struct BreathCase {
        name: String,
        attacker: SimpleCombatantStats,
        defender: SimpleCombatantStats,
        #[serde(rename = "attackerBreath", default)]
        attacker_breath: Option<SimpleBreathProfile>,
        #[serde(rename = "defenderBreath", default)]
        defender_breath: Option<SimpleBreathProfile>,
        #[serde(rename = "maxTimeSec")]
        max_time_sec: f64,
        #[serde(rename = "expectedSummary")]
        expected: BestBuildsMatchupSummary,
    }

    #[derive(Deserialize, Default)]
    #[serde(rename_all = "camelCase", default)]
    struct FixtureLifeLeechSide {
        available: bool,
        life_leech_value: f64,
    }

    #[derive(Deserialize, Default)]
    #[serde(rename_all = "camelCase", default)]
    struct FixtureLifeLeechProfile {
        attacker: FixtureLifeLeechSide,
        defender: FixtureLifeLeechSide,
    }

    #[derive(Deserialize)]
    struct LifeLeechBreathCase {
        name: String,
        attacker: SimpleCombatantStats,
        defender: SimpleCombatantStats,
        #[serde(rename = "attackerBreath", default)]
        attacker_breath: Option<SimpleBreathProfile>,
        #[serde(rename = "defenderBreath", default)]
        defender_breath: Option<SimpleBreathProfile>,
        #[serde(rename = "lifeLeechProfile", default)]
        life_leech_profile: FixtureLifeLeechProfile,
        #[serde(rename = "abilityPolicy", default)]
        ability_policy: String,
        #[serde(rename = "maxTimeSec")]
        max_time_sec: f64,
        #[serde(rename = "expectedSummary")]
        expected: BestBuildsMatchupSummary,
    }

    /// activeProfile.attacker / activeProfile.defender format used in simple_active_melee_matchups.json
    #[derive(Deserialize, Default)]
    #[serde(rename_all = "camelCase", default)]
    struct FixtureActiveProfile {
        spite_value: Option<f64>,
        harden_available: bool,
        fortify_available: bool,
        frost_nova_available: bool,
        warden_rage_available: bool,
        adrenaline_available: bool,
        hunters_curse_available: bool,
        unbridled_rage_available: bool,
        drowsy_area_available: bool,
        rewind_available: bool,
        #[serde(default)]
        aura_subtype: Option<String>,
        frost_snare_available: bool,
        poison_area_available: bool,
        yolk_bomb_available: bool,
        yolk_bomb_value: Option<String>,
        divination_available: bool,
        cursed_sigil_stacks: f64,
        thorn_trap_available: bool,
    }

    #[derive(Deserialize, Default)]
    #[serde(rename_all = "camelCase", default)]
    struct FixtureActivePair {
        attacker: FixtureActiveProfile,
        defender: FixtureActiveProfile,
    }

    #[derive(Deserialize)]
    struct ActiveMeleeCase {
        name: String,
        attacker: SimpleCombatantStats,
        defender: SimpleCombatantStats,
        #[serde(rename = "activeProfile", default)]
        active_profile: FixtureActivePair,
        #[serde(rename = "abilityPolicy")]
        ability_policy: String,
        #[serde(rename = "maxTimeSec")]
        max_time_sec: f64,
        #[serde(rename = "expectedSummary")]
        expected: BestBuildsMatchupSummary,
    }

    // ─── Helpers ─────────────────────────────────────────────────────────────

    fn policy_from_str(s: &str) -> SimpleAbilityTimingMode {
        match s {
            "ideal" => SimpleAbilityTimingMode::Ideal,
            "extreme" => SimpleAbilityTimingMode::Extreme,
            "fast" => SimpleAbilityTimingMode::Fast,
            "reallyFast" => SimpleAbilityTimingMode::ReallyFast,
            _ => SimpleAbilityTimingMode::SemiIdeal,
        }
    }

    fn active_config_from_profile(
        pair: &FixtureActivePair,
        attacker: &crate::contracts::SimpleCombatantStats,
        defender: &crate::contracts::SimpleCombatantStats,
    ) -> ComposableAbilityConfig {
        ComposableAbilityConfig {
            attacker_thorn_trap: pair.attacker.thorn_trap_available,
            defender_thorn_trap: pair.defender.thorn_trap_available,
            attacker_frost_snare: pair.attacker.frost_snare_available,
            defender_frost_snare: pair.defender.frost_snare_available,
            attacker_poison_area: pair.attacker.poison_area_available,
            defender_poison_area: pair.defender.poison_area_available,
            attacker_yolk_bomb: pair.attacker.yolk_bomb_available,
            defender_yolk_bomb: pair.defender.yolk_bomb_available,
            attacker_yolk_bomb_value: pair.attacker.yolk_bomb_value.clone(),
            defender_yolk_bomb_value: pair.defender.yolk_bomb_value.clone(),
            attacker_divination: pair.attacker.divination_available,
            defender_divination: pair.defender.divination_available,
            attacker_aura_subtype: pair.attacker.aura_subtype.clone(),
            defender_aura_subtype: pair.defender.aura_subtype.clone(),
            attacker_cursed_sigil_stacks: pair.attacker.cursed_sigil_stacks,
            defender_cursed_sigil_stacks: pair.defender.cursed_sigil_stacks,
            attacker_fortify: pair.attacker.fortify_available,
            defender_fortify: pair.defender.fortify_available,
            attacker_drowsy_area: pair.attacker.drowsy_area_available,
            defender_drowsy_area: pair.defender.drowsy_area_available,
            attacker_unbridled_rage: pair.attacker.unbridled_rage_available,
            defender_unbridled_rage: pair.defender.unbridled_rage_available,
            attacker_hunters_curse: pair.attacker.hunters_curse_available,
            defender_hunters_curse: pair.defender.hunters_curse_available,
            attacker_life_leech_value: 0.0,
            defender_life_leech_value: 0.0,
            attacker_rewind: pair.attacker.rewind_available,
            defender_rewind: pair.defender.rewind_available,
            attacker_warden_rage: pair.attacker.warden_rage_available,
            defender_warden_rage: pair.defender.warden_rage_available,
            attacker_adrenaline: pair.attacker.adrenaline_available,
            defender_adrenaline: pair.defender.adrenaline_available,
            attacker_lich_mark: false,
            defender_lich_mark: false,
            attacker_lich_mark_payload_status_id: None,
            defender_lich_mark_payload_status_id: None,
            // Harden: explicit active ability flag from fixture profile
            attacker_harden: pair.attacker.harden_available,
            defender_harden: pair.defender.harden_available,
            // Hunker: auto-enabled from stats (mirrors TS: attackerHunker = getHunkerReductionPct > 0)
            attacker_hunker: attacker.hunker_reduction_pct > 0.0,
            defender_hunker: defender.hunker_reduction_pct > 0.0,
            // Spite: active ability value from fixture profile
            attacker_spite_value: pair.attacker.spite_value.unwrap_or(0.0),
            defender_spite_value: pair.defender.spite_value.unwrap_or(0.0),
            // Frost Nova: explicit active ability flag from fixture profile
            attacker_frost_nova: pair.attacker.frost_nova_available,
            defender_frost_nova: pair.defender.frost_nova_available,
            ..Default::default()
        }
    }

    fn assert_summary_approx(got: &BestBuildsMatchupSummary, exp: &BestBuildsMatchupSummary, case: &str) {
        assert_eq!(got.winner, exp.winner, "[{case}] winner mismatch");
        assert!(
            (got.ttk_a_to_b - exp.ttk_a_to_b).abs() < FLOAT_TOL,
            "[{case}] ttkAtoB: got={:.3} exp={:.3} diff={:.4}",
            got.ttk_a_to_b, exp.ttk_a_to_b, (got.ttk_a_to_b - exp.ttk_a_to_b).abs()
        );
        if let Some(exp_death) = exp.death_time_a {
            let got_death = got.death_time_a.unwrap_or(got.max_time_sec);
            assert!(
                (got_death - exp_death).abs() < FLOAT_TOL,
                "[{case}] deathTimeA: got={:.3} exp={:.3}",
                got_death, exp_death
            );
        }
    }

    // ─── Tests ───────────────────────────────────────────────────────────────

    #[test]
    fn fixture_simple_melee() {
        let json = include_str!("../fixtures/simple_melee_matchups.json");
        let cases: Vec<MeleeCase> = serde_json::from_str(json).expect("parse simple_melee");
        for c in &cases {
            let config = ComposableAbilityConfig::default();
            let got = simulate_composable_matchup(
                &c.attacker, &c.defender, None, None,
                SimpleAbilityTimingMode::SemiIdeal, &config, c.max_time_sec,
            );
            assert_summary_approx(&got, &c.expected, &c.name);
        }
    }

    #[test]
    fn fixture_simple_breath() {
        let json = include_str!("../fixtures/simple_breath_matchups.json");
        let cases: Vec<BreathCase> = serde_json::from_str(json).expect("parse simple_breath");
        for c in &cases {
            let config = ComposableAbilityConfig::default();
            let got = simulate_composable_matchup(
                &c.attacker, &c.defender,
                c.attacker_breath.as_ref(), c.defender_breath.as_ref(),
                SimpleAbilityTimingMode::SemiIdeal, &config, c.max_time_sec,
            );
            assert_summary_approx(&got, &c.expected, &c.name);
        }
    }

    #[test]
    fn fixture_simple_status_melee() {
        let json = include_str!("../fixtures/simple_status_melee_matchups.json");
        let cases: Vec<MeleeCase> = serde_json::from_str(json).expect("parse simple_status_melee");
        for c in &cases {
            let config = ComposableAbilityConfig::default();
            let got = simulate_composable_matchup(
                &c.attacker, &c.defender, None, None,
                SimpleAbilityTimingMode::SemiIdeal, &config, c.max_time_sec,
            );
            assert_summary_approx(&got, &c.expected, &c.name);
        }
    }

    #[test]
    fn fixture_simple_active_melee() {
        let json = include_str!("../fixtures/simple_active_melee_matchups.json");
        let cases: Vec<ActiveMeleeCase> = serde_json::from_str(json).expect("parse simple_active_melee");
        for c in &cases {
            let config = active_config_from_profile(&c.active_profile, &c.attacker, &c.defender);
            let policy = policy_from_str(&c.ability_policy);
            let got = simulate_composable_matchup(
                &c.attacker, &c.defender, None, None,
                policy, &config, c.max_time_sec,
            );
            assert_summary_approx(&got, &c.expected, &c.name);
        }
    }

    #[test]
    fn fixture_hunters_curse_breath() {
        let json = include_str!("../fixtures/simple_hunters_curse_breath_matchups.json");
        let cases: Vec<BreathCase> = serde_json::from_str(json).expect("parse hunters_curse_breath");
        for c in &cases {
            let mut config = ComposableAbilityConfig::default();
            config.attacker_hunters_curse = true;
            let got = simulate_composable_matchup(
                &c.attacker, &c.defender,
                c.attacker_breath.as_ref(), c.defender_breath.as_ref(),
                SimpleAbilityTimingMode::SemiIdeal, &config, c.max_time_sec,
            );
            assert_summary_approx(&got, &c.expected, &c.name);
        }
    }

    #[test]
    fn fixture_unbridled_rage_breath() {
        let json = include_str!("../fixtures/simple_unbridled_rage_breath_matchups.json");
        let cases: Vec<BreathCase> = serde_json::from_str(json).expect("parse unbridled_rage_breath");
        for c in &cases {
            let mut config = ComposableAbilityConfig::default();
            config.attacker_unbridled_rage = true;
            let got = simulate_composable_matchup(
                &c.attacker, &c.defender,
                c.attacker_breath.as_ref(), c.defender_breath.as_ref(),
                SimpleAbilityTimingMode::SemiIdeal, &config, c.max_time_sec,
            );
            assert_summary_approx(&got, &c.expected, &c.name);
        }
    }

    #[test]
    fn fixture_life_leech_breath() {
        let json = include_str!("../fixtures/simple_life_leech_breath_matchups.json");
        let cases: Vec<LifeLeechBreathCase> = serde_json::from_str(json).expect("parse life_leech_breath");
        for c in &cases {
            let mut config = ComposableAbilityConfig::default();
            if c.life_leech_profile.attacker.available {
                config.attacker_life_leech_value = c.life_leech_profile.attacker.life_leech_value;
            }
            if c.life_leech_profile.defender.available {
                config.defender_life_leech_value = c.life_leech_profile.defender.life_leech_value;
            }
            let policy = policy_from_str(&c.ability_policy);
            let got = simulate_composable_matchup(
                &c.attacker, &c.defender,
                c.attacker_breath.as_ref(), c.defender_breath.as_ref(),
                policy, &config, c.max_time_sec,
            );
            assert_summary_approx(&got, &c.expected, &c.name);
        }
    }

    #[test]
    fn fixture_life_leech_melee() {
        let json = include_str!("../fixtures/simple_life_leech_melee_matchups.json");
        let cases: Vec<MeleeCase> = serde_json::from_str(json).expect("parse life_leech_melee");
        for c in &cases {
            let config = ComposableAbilityConfig::default();
            let got = simulate_composable_matchup(
                &c.attacker, &c.defender, None, None,
                SimpleAbilityTimingMode::SemiIdeal, &config, c.max_time_sec,
            );
            assert_summary_approx(&got, &c.expected, &c.name);
        }
    }

    /// Rust-native fixture regeneration / drift reporter.
    ///
    /// Replaces the retired TS fixture generators, which ran the now-deleted TS
    /// combat engine as the migration oracle. Runs the live composable engine
    /// over every consumed `simple_*` fixture and prints a `FIXTURE_REGEN_DIFF`
    /// line for each case whose output no longer matches the recorded
    /// `expectedSummary` (winner / ttk / death-time beyond FLOAT_TOL). The
    /// config/policy setup for each fixture mirrors its assertion test above.
    ///
    /// Marked `#[ignore]` so it never runs in the normal suite. Invoke:
    /// `cargo test --lib regenerate_stale_fixtures -- --ignored --nocapture`.
    ///
    /// Zero output = the engine still matches every frozen golden fixture.
    /// After an *intentional* engine-model change, copy each printed summary
    /// into the matching `expectedSummary` block (reviewing the diff). Golden
    /// fixtures are deliberately not auto-rewritten: blind regeneration would
    /// just re-bless current behaviour, defeating the regression guard.
    #[test]
    #[ignore]
    fn regenerate_stale_fixtures() {
        fn report(case: &str, got: &BestBuildsMatchupSummary, exp: &BestBuildsMatchupSummary) {
            let winner_diff = got.winner != exp.winner;
            let ttk_diff = (got.ttk_a_to_b - exp.ttk_a_to_b).abs() > FLOAT_TOL;
            let death_diff = match (got.death_time_a, exp.death_time_a) {
                (Some(g), Some(e)) => (g - e).abs() > FLOAT_TOL,
                (None, None) => false,
                _ => true,
            };
            if !winner_diff && !ttk_diff && !death_diff {
                return;
            }
            eprintln!(
                "FIXTURE_REGEN_DIFF [{case}] winner={:?} ttkAtoB={:.6} deathTimeA={:?} dpsAtoB={:.6} damageDealtA={:.6} damageDealtAAtBDeath={:.6} extendedDamagePotentialA={:.6}",
                got.winner, got.ttk_a_to_b, got.death_time_a,
                got.dps_a_to_b, got.damage_dealt_a, got.damage_dealt_a_at_b_death,
                got.extended_damage_potential_a,
            );
        }

        // Plain melee - default config, no breath, SemiIdeal.
        for fixture in [
            include_str!("../fixtures/simple_melee_matchups.json"),
            include_str!("../fixtures/simple_status_melee_matchups.json"),
            include_str!("../fixtures/simple_life_leech_melee_matchups.json"),
        ] {
            for c in serde_json::from_str::<Vec<MeleeCase>>(fixture).expect("parse melee").iter() {
                let config = ComposableAbilityConfig::default();
                let got = simulate_composable_matchup(
                    &c.attacker, &c.defender, None, None,
                    SimpleAbilityTimingMode::SemiIdeal, &config, c.max_time_sec,
                );
                report(&c.name, &got, &c.expected);
            }
        }

        // Breath - default config (simple_breath) and the single-active variants.
        let breath_cases: [(&str, bool, bool); 3] = [
            (include_str!("../fixtures/simple_breath_matchups.json"), false, false),
            (include_str!("../fixtures/simple_hunters_curse_breath_matchups.json"), true, false),
            (include_str!("../fixtures/simple_unbridled_rage_breath_matchups.json"), false, true),
        ];
        for (fixture, hunters_curse, unbridled_rage) in breath_cases {
            for c in serde_json::from_str::<Vec<BreathCase>>(fixture).expect("parse breath").iter() {
                let mut config = ComposableAbilityConfig::default();
                config.attacker_hunters_curse = hunters_curse;
                config.attacker_unbridled_rage = unbridled_rage;
                let got = simulate_composable_matchup(
                    &c.attacker, &c.defender,
                    c.attacker_breath.as_ref(), c.defender_breath.as_ref(),
                    SimpleAbilityTimingMode::SemiIdeal, &config, c.max_time_sec,
                );
                report(&c.name, &got, &c.expected);
            }
        }

        // Active melee - config + policy from the per-case profile.
        for c in serde_json::from_str::<Vec<ActiveMeleeCase>>(include_str!(
            "../fixtures/simple_active_melee_matchups.json"
        ))
        .expect("parse")
        .iter()
        {
            let config = active_config_from_profile(&c.active_profile, &c.attacker, &c.defender);
            let policy = policy_from_str(&c.ability_policy);
            let got = simulate_composable_matchup(
                &c.attacker, &c.defender, None, None,
                policy, &config, c.max_time_sec,
            );
            report(&c.name, &got, &c.expected);
        }

        // Life-leech breath - LL value + policy from the per-case profile.
        for c in serde_json::from_str::<Vec<LifeLeechBreathCase>>(include_str!(
            "../fixtures/simple_life_leech_breath_matchups.json"
        ))
        .expect("parse")
        .iter()
        {
            let mut config = ComposableAbilityConfig::default();
            if c.life_leech_profile.attacker.available {
                config.attacker_life_leech_value = c.life_leech_profile.attacker.life_leech_value;
            }
            if c.life_leech_profile.defender.available {
                config.defender_life_leech_value = c.life_leech_profile.defender.life_leech_value;
            }
            let policy = policy_from_str(&c.ability_policy);
            let got = simulate_composable_matchup(
                &c.attacker, &c.defender,
                c.attacker_breath.as_ref(), c.defender_breath.as_ref(),
                policy, &config, c.max_time_sec,
            );
            report(&c.name, &got, &c.expected);
        }
    }
}
