/// Fixture-based parity tests: composable engine must match TS-generated expected values.
///
/// Fixtures live in wasm-engine/fixtures/. They were generated by the TS combat
/// engine, which was deleted in the 2026 cleanup, so nothing regenerates them
/// now - they are frozen goldens, and an expected value only moves by hand.
/// When a test fails, check whether:
///   1. Rust has a bug on this mechanic - fix Rust
///   2. The mechanic changed on purpose - move the expected value and say in the
///      commit what the new number was checked against. A drift is not evidence
///      of a regression on its own: the numbers here record what the old TS
///      engine did, not what the game does.
///
/// Tolerance: winner must be exact; TTK / death time within FLOAT_TOL (0.05s).
#[cfg(test)]
#[allow(clippy::module_inception)] // established test-module name; renaming churns all use-paths for no gain
mod fixture_tests {
    use crate::composable::{simulate_composable_matchup, ComposableAbilityConfig};
    use crate::contracts::{
        BestBuildsMatchupSummary, SimpleCombatantStats, SimpleBreathProfile,
    };
    use crate::contracts::SimpleAbilityTimingMode;
    use serde::Deserialize;

    const FLOAT_TOL: f64 = 0.05;

    // Fixture case types

    #[derive(Deserialize)]
    struct MeleeCase {
        name: String,
        attacker: SimpleCombatantStats,
        defender: SimpleCombatantStats,
        #[serde(rename = "maxTimeSec")]
        max_time_sec: f64,
        #[serde(rename = "expectedSummary")]
        expected: serde_json::Value,
    }

    #[derive(Deserialize)]
    struct BreathCase {
        name: String,
        attacker: SimpleCombatantStats,
        defender: SimpleCombatantStats,
        #[serde(rename = "attackerBreath", default)]
        attacker_breath: Option<SimpleBreathProfile>,
        #[serde(rename = "defenderBreath", default)]
        defender_breath: Option<SimpleBreathProfile>,
        #[serde(rename = "maxTimeSec")]
        max_time_sec: f64,
        #[serde(rename = "expectedSummary")]
        expected: serde_json::Value,
    }

    #[derive(Deserialize, Default)]
    #[serde(rename_all = "camelCase", default)]
    struct FixtureLifeLeechSide {
        available: bool,
        life_leech_value: f64,
    }

    #[derive(Deserialize, Default)]
    #[serde(rename_all = "camelCase", default)]
    struct FixtureLifeLeechProfile {
        attacker: FixtureLifeLeechSide,
        defender: FixtureLifeLeechSide,
    }

    #[derive(Deserialize)]
    struct LifeLeechBreathCase {
        name: String,
        attacker: SimpleCombatantStats,
        defender: SimpleCombatantStats,
        #[serde(rename = "attackerBreath", default)]
        attacker_breath: Option<SimpleBreathProfile>,
        #[serde(rename = "defenderBreath", default)]
        defender_breath: Option<SimpleBreathProfile>,
        #[serde(rename = "lifeLeechProfile", default)]
        life_leech_profile: FixtureLifeLeechProfile,
        #[serde(rename = "abilityPolicy", default)]
        ability_policy: String,
        #[serde(rename = "maxTimeSec")]
        max_time_sec: f64,
        #[serde(rename = "expectedSummary")]
        expected: serde_json::Value,
    }

    /// activeProfile.attacker / activeProfile.defender format used in simple_active_melee_matchups.json
    #[derive(Deserialize, Default)]
    #[serde(rename_all = "camelCase", default)]
    struct FixtureActiveProfile {
        spite_value: Option<f64>,
        harden_available: bool,
        fortify_available: bool,
        frost_nova_available: bool,
        warden_rage_available: bool,
        adrenaline_available: bool,
        hunters_curse_available: bool,
        unbridled_rage_available: bool,
        drowsy_area_available: bool,
        rewind_available: bool,
        #[serde(default)]
        aura_subtype: Option<String>,
        frost_snare_available: bool,
        poison_area_available: bool,
        yolk_bomb_available: bool,
        yolk_bomb_value: Option<String>,
        divination_available: bool,
        cursed_sigil_stacks: f64,
        thorn_trap_available: bool,
    }

    #[derive(Deserialize, Default)]
    #[serde(rename_all = "camelCase", default)]
    struct FixtureActivePair {
        attacker: FixtureActiveProfile,
        defender: FixtureActiveProfile,
    }

    #[derive(Deserialize)]
    struct ActiveMeleeCase {
        name: String,
        attacker: SimpleCombatantStats,
        defender: SimpleCombatantStats,
        #[serde(rename = "activeProfile", default)]
        active_profile: FixtureActivePair,
        #[serde(rename = "abilityPolicy")]
        ability_policy: String,
        #[serde(rename = "maxTimeSec")]
        max_time_sec: f64,
        #[serde(rename = "expectedSummary")]
        expected: serde_json::Value,
    }

    // Helpers

    fn policy_from_str(s: &str) -> SimpleAbilityTimingMode {
        match s {
            "ideal" => SimpleAbilityTimingMode::Ideal,
            "extreme" => SimpleAbilityTimingMode::Extreme,
            "fast" => SimpleAbilityTimingMode::Fast,
            "reallyFast" => SimpleAbilityTimingMode::ReallyFast,
            _ => SimpleAbilityTimingMode::SemiIdeal,
        }
    }

    fn active_config_from_profile(
        pair: &FixtureActivePair,
        attacker: &crate::contracts::SimpleCombatantStats,
        defender: &crate::contracts::SimpleCombatantStats,
    ) -> ComposableAbilityConfig {
        ComposableAbilityConfig {
            attacker_thorn_trap: pair.attacker.thorn_trap_available,
            defender_thorn_trap: pair.defender.thorn_trap_available,
            attacker_frost_snare: pair.attacker.frost_snare_available,
            defender_frost_snare: pair.defender.frost_snare_available,
            attacker_poison_area: pair.attacker.poison_area_available,
            defender_poison_area: pair.defender.poison_area_available,
            attacker_yolk_bomb: pair.attacker.yolk_bomb_available,
            defender_yolk_bomb: pair.defender.yolk_bomb_available,
            attacker_yolk_bomb_value: pair.attacker.yolk_bomb_value.clone(),
            defender_yolk_bomb_value: pair.defender.yolk_bomb_value.clone(),
            attacker_divination: pair.attacker.divination_available,
            defender_divination: pair.defender.divination_available,
            attacker_aura_subtype: pair.attacker.aura_subtype.clone(),
            defender_aura_subtype: pair.defender.aura_subtype.clone(),
            attacker_cursed_sigil_stacks: pair.attacker.cursed_sigil_stacks,
            defender_cursed_sigil_stacks: pair.defender.cursed_sigil_stacks,
            attacker_fortify: pair.attacker.fortify_available,
            defender_fortify: pair.defender.fortify_available,
            attacker_drowsy_area: pair.attacker.drowsy_area_available,
            defender_drowsy_area: pair.defender.drowsy_area_available,
            attacker_unbridled_rage: pair.attacker.unbridled_rage_available,
            defender_unbridled_rage: pair.defender.unbridled_rage_available,
            attacker_hunters_curse: pair.attacker.hunters_curse_available,
            defender_hunters_curse: pair.defender.hunters_curse_available,
            attacker_life_leech_value: 0.0,
            defender_life_leech_value: 0.0,
            attacker_rewind: pair.attacker.rewind_available,
            defender_rewind: pair.defender.rewind_available,
            attacker_warden_rage: pair.attacker.warden_rage_available,
            defender_warden_rage: pair.defender.warden_rage_available,
            attacker_adrenaline: pair.attacker.adrenaline_available,
            defender_adrenaline: pair.defender.adrenaline_available,
            attacker_lich_mark: false,
            defender_lich_mark: false,
            attacker_lich_mark_payload_status_id: None,
            defender_lich_mark_payload_status_id: None,
            // Harden: explicit active ability flag from fixture profile
            attacker_harden: pair.attacker.harden_available,
            defender_harden: pair.defender.harden_available,
            // Hunker: auto-enabled from stats (mirrors TS: attackerHunker = getHunkerReductionPct > 0)
            attacker_hunker: attacker.hunker_reduction_pct > 0.0,
            defender_hunker: defender.hunker_reduction_pct > 0.0,
            // Spite: active ability value from fixture profile
            attacker_spite_value: pair.attacker.spite_value.unwrap_or(0.0),
            defender_spite_value: pair.defender.spite_value.unwrap_or(0.0),
            // Frost Nova: explicit active ability flag from fixture profile
            attacker_frost_nova: pair.attacker.frost_nova_available,
            defender_frost_nova: pair.defender.frost_nova_available,
            ..Default::default()
        }
    }

    /// One field's fresh value vs its recorded value: winner/strings/null exact;
    /// numbers within FLOAT_TOL plus a relative epsilon (absorbs cross-run float
    /// noise but not a real change). A field the engine no longer emits = mismatch.
    fn field_matches(got_field: Option<&serde_json::Value>, exp: &serde_json::Value) -> bool {
        match (got_field, exp) {
            (Some(serde_json::Value::Number(g)), serde_json::Value::Number(e)) => {
                let gf = g.as_f64().unwrap_or(f64::NAN);
                let ef = e.as_f64().unwrap_or(f64::NAN);
                (gf - ef).abs() <= FLOAT_TOL + 1e-6 * gf.abs().max(ef.abs())
            }
            (Some(g), e) => g == e,
            (None, _) => false,
        }
    }

    /// Diff a fresh summary against a recorded `expectedSummary` JSON object,
    /// checking every key the fixture actually stores. Driving off the JSON's
    /// present keys - not the typed struct - avoids comparing fields a fixture
    /// never recorded (they would deserialize to defaults and false-fail).
    /// Returns one message per drifting field.
    fn summary_diffs(got: &BestBuildsMatchupSummary, expected: &serde_json::Value) -> Vec<String> {
        let exp_map = match expected.as_object() {
            Some(m) => m,
            None => return vec!["expectedSummary is not a JSON object".to_string()],
        };
        let got_val = serde_json::to_value(got).expect("serialize summary");
        let got_map = got_val.as_object().expect("summary serializes to an object");
        let mut diffs = Vec::new();
        for (key, exp) in exp_map {
            let got_field = got_map.get(key);
            if !field_matches(got_field, exp) {
                diffs.push(format!(
                    "{key}: got={} exp={}",
                    got_field.map_or_else(|| "<missing>".to_string(), std::string::ToString::to_string),
                    exp
                ));
            }
        }
        diffs
    }

    fn assert_summary(got: &BestBuildsMatchupSummary, expected: &serde_json::Value, case: &str) {
        let diffs = summary_diffs(got, expected);
        assert!(
            diffs.is_empty(),
            "[{case}] summary drift on {} field(s):\n    {}",
            diffs.len(),
            diffs.join("\n    ")
        );
    }

    // Tests

    #[test]
    fn fixture_simple_melee() {
        let json = include_str!("../fixtures/simple_melee_matchups.json");
        let cases: Vec<MeleeCase> = serde_json::from_str(json).expect("parse simple_melee");
        for c in &cases {
            let config = ComposableAbilityConfig::default();
            let got = simulate_composable_matchup(
                &c.attacker, &c.defender, None, None,
                SimpleAbilityTimingMode::SemiIdeal, &config, c.max_time_sec,
            );
            assert_summary(&got, &c.expected, &c.name);
        }
    }

    #[test]
    fn fixture_simple_breath() {
        let json = include_str!("../fixtures/simple_breath_matchups.json");
        let cases: Vec<BreathCase> = serde_json::from_str(json).expect("parse simple_breath");
        for c in &cases {
            let config = ComposableAbilityConfig::default();
            let got = simulate_composable_matchup(
                &c.attacker, &c.defender,
                c.attacker_breath.as_ref(), c.defender_breath.as_ref(),
                SimpleAbilityTimingMode::SemiIdeal, &config, c.max_time_sec,
            );
            assert_summary(&got, &c.expected, &c.name);
        }
    }

    #[test]
    fn fixture_simple_status_melee() {
        let json = include_str!("../fixtures/simple_status_melee_matchups.json");
        let cases: Vec<MeleeCase> = serde_json::from_str(json).expect("parse simple_status_melee");
        for c in &cases {
            let config = ComposableAbilityConfig::default();
            let got = simulate_composable_matchup(
                &c.attacker, &c.defender, None, None,
                SimpleAbilityTimingMode::SemiIdeal, &config, c.max_time_sec,
            );
            assert_summary(&got, &c.expected, &c.name);
        }
    }

    #[test]
    fn fixture_simple_active_melee() {
        let json = include_str!("../fixtures/simple_active_melee_matchups.json");
        let cases: Vec<ActiveMeleeCase> = serde_json::from_str(json).expect("parse simple_active_melee");
        for c in &cases {
            let config = active_config_from_profile(&c.active_profile, &c.attacker, &c.defender);
            let policy = policy_from_str(&c.ability_policy);
            let got = simulate_composable_matchup(
                &c.attacker, &c.defender, None, None,
                policy, &config, c.max_time_sec,
            );
            assert_summary(&got, &c.expected, &c.name);
        }
    }

    #[test]
    fn fixture_hunters_curse_breath() {
        let json = include_str!("../fixtures/simple_hunters_curse_breath_matchups.json");
        let cases: Vec<BreathCase> = serde_json::from_str(json).expect("parse hunters_curse_breath");
        for c in &cases {
            let mut config = ComposableAbilityConfig::default();
            config.attacker_hunters_curse = true;
            let got = simulate_composable_matchup(
                &c.attacker, &c.defender,
                c.attacker_breath.as_ref(), c.defender_breath.as_ref(),
                SimpleAbilityTimingMode::SemiIdeal, &config, c.max_time_sec,
            );
            assert_summary(&got, &c.expected, &c.name);
        }
    }

    #[test]
    fn fixture_unbridled_rage_breath() {
        let json = include_str!("../fixtures/simple_unbridled_rage_breath_matchups.json");
        let cases: Vec<BreathCase> = serde_json::from_str(json).expect("parse unbridled_rage_breath");
        for c in &cases {
            let mut config = ComposableAbilityConfig::default();
            config.attacker_unbridled_rage = true;
            let got = simulate_composable_matchup(
                &c.attacker, &c.defender,
                c.attacker_breath.as_ref(), c.defender_breath.as_ref(),
                SimpleAbilityTimingMode::SemiIdeal, &config, c.max_time_sec,
            );
            assert_summary(&got, &c.expected, &c.name);
        }
    }

    #[test]
    fn fixture_life_leech_breath() {
        let json = include_str!("../fixtures/simple_life_leech_breath_matchups.json");
        let cases: Vec<LifeLeechBreathCase> = serde_json::from_str(json).expect("parse life_leech_breath");
        for c in &cases {
            let mut config = ComposableAbilityConfig::default();
            if c.life_leech_profile.attacker.available {
                config.attacker_life_leech_value = c.life_leech_profile.attacker.life_leech_value;
            }
            if c.life_leech_profile.defender.available {
                config.defender_life_leech_value = c.life_leech_profile.defender.life_leech_value;
            }
            let policy = policy_from_str(&c.ability_policy);
            let got = simulate_composable_matchup(
                &c.attacker, &c.defender,
                c.attacker_breath.as_ref(), c.defender_breath.as_ref(),
                policy, &config, c.max_time_sec,
            );
            assert_summary(&got, &c.expected, &c.name);
        }
    }

    #[test]
    fn fixture_life_leech_melee() {
        let json = include_str!("../fixtures/simple_life_leech_melee_matchups.json");
        let cases: Vec<MeleeCase> = serde_json::from_str(json).expect("parse life_leech_melee");
        for c in &cases {
            let config = ComposableAbilityConfig::default();
            let got = simulate_composable_matchup(
                &c.attacker, &c.defender, None, None,
                SimpleAbilityTimingMode::SemiIdeal, &config, c.max_time_sec,
            );
            assert_summary(&got, &c.expected, &c.name);
        }
    }

    /// Fixture drift reporter + regenerator.
    ///
    /// Runs the live composable engine over every consumed `simple_*` fixture and
    /// compares each case to its recorded `expectedSummary` on every stored field
    /// (the same comparison the assertion tests use). `#[ignore]` so it never runs
    /// in the normal suite:
    ///   - Verify (default): `cargo test --lib regenerate_stale_fixtures -- --ignored --nocapture`
    ///     prints a `FIXTURE_DRIFT` block per drifting case; zero output = no drift.
    ///   - Regenerate: `UPDATE_FIXTURES=1 cargo test --lib regenerate_stale_fixtures -- --ignored`
    ///     rewrites the drifting `expectedSummary` values in place (present keys
    ///     only, key order preserved), then commit the reviewed diff.
    ///
    /// Regeneration is opt-in: CI passes no env var, so the gate can never
    /// blind-re-bless itself - a real regression keeps failing the assertion tests
    /// until a human runs the regenerator and reviews the diff.
    #[test]
    #[ignore]
    fn regenerate_stale_fixtures() {
        use serde_json::Value;

        type RunFn = Box<dyn Fn(&Value) -> BestBuildsMatchupSummary>;

        fn run_melee(case: &Value) -> BestBuildsMatchupSummary {
            let c: MeleeCase = serde_json::from_value(case.clone()).expect("melee case");
            simulate_composable_matchup(
                &c.attacker, &c.defender, None, None,
                SimpleAbilityTimingMode::SemiIdeal, &ComposableAbilityConfig::default(), c.max_time_sec,
            )
        }
        fn run_breath(case: &Value, hunters_curse: bool, unbridled_rage: bool) -> BestBuildsMatchupSummary {
            let c: BreathCase = serde_json::from_value(case.clone()).expect("breath case");
            let mut config = ComposableAbilityConfig::default();
            config.attacker_hunters_curse = hunters_curse;
            config.attacker_unbridled_rage = unbridled_rage;
            simulate_composable_matchup(
                &c.attacker, &c.defender,
                c.attacker_breath.as_ref(), c.defender_breath.as_ref(),
                SimpleAbilityTimingMode::SemiIdeal, &config, c.max_time_sec,
            )
        }
        fn run_active(case: &Value) -> BestBuildsMatchupSummary {
            let c: ActiveMeleeCase = serde_json::from_value(case.clone()).expect("active case");
            let config = active_config_from_profile(&c.active_profile, &c.attacker, &c.defender);
            simulate_composable_matchup(
                &c.attacker, &c.defender, None, None,
                policy_from_str(&c.ability_policy), &config, c.max_time_sec,
            )
        }
        fn run_life_leech_breath(case: &Value) -> BestBuildsMatchupSummary {
            let c: LifeLeechBreathCase = serde_json::from_value(case.clone()).expect("life-leech case");
            let mut config = ComposableAbilityConfig::default();
            if c.life_leech_profile.attacker.available {
                config.attacker_life_leech_value = c.life_leech_profile.attacker.life_leech_value;
            }
            if c.life_leech_profile.defender.available {
                config.defender_life_leech_value = c.life_leech_profile.defender.life_leech_value;
            }
            simulate_composable_matchup(
                &c.attacker, &c.defender,
                c.attacker_breath.as_ref(), c.defender_breath.as_ref(),
                policy_from_str(&c.ability_policy), &config, c.max_time_sec,
            )
        }

        let fixtures: Vec<(&str, RunFn)> = vec![
            ("simple_melee_matchups.json", Box::new(run_melee)),
            ("simple_status_melee_matchups.json", Box::new(run_melee)),
            ("simple_life_leech_melee_matchups.json", Box::new(run_melee)),
            ("simple_breath_matchups.json", Box::new(|c| run_breath(c, false, false))),
            ("simple_hunters_curse_breath_matchups.json", Box::new(|c| run_breath(c, true, false))),
            ("simple_unbridled_rage_breath_matchups.json", Box::new(|c| run_breath(c, false, true))),
            ("simple_active_melee_matchups.json", Box::new(run_active)),
            ("simple_life_leech_breath_matchups.json", Box::new(run_life_leech_breath)),
        ];

        let update = std::env::var("UPDATE_FIXTURES").is_ok();
        let mut drift_total = 0usize;
        for (name, run) in &fixtures {
            let path = format!(concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures/{}"), name);
            let text = std::fs::read_to_string(&path).expect("read fixture file");
            let mut cases: Vec<Value> = serde_json::from_str(&text).expect("parse fixture array");
            let mut changed = false;
            for case in &mut cases {
                let label = case.get("name").and_then(Value::as_str).unwrap_or("?").to_string();
                let got = run(case);
                let expected = case.get("expectedSummary").cloned().unwrap_or(Value::Null);
                let diffs = summary_diffs(&got, &expected);
                if diffs.is_empty() {
                    continue;
                }
                if update {
                    let got_val = serde_json::to_value(&got).expect("serialize summary");
                    if let (Some(exp_obj), Some(got_obj)) = (
                        case.get_mut("expectedSummary").and_then(Value::as_object_mut),
                        got_val.as_object(),
                    ) {
                        // Rewrite only the keys that actually drifted, in place -
                        // key order preserved, unchanged values (incl. their int
                        // vs float form) left byte-for-byte.
                        for (key, value) in exp_obj.iter_mut() {
                            if let Some(fresh) = got_obj.get(key) {
                                if !field_matches(Some(fresh), value) {
                                    *value = fresh.clone();
                                }
                            }
                        }
                        changed = true;
                    }
                } else {
                    drift_total += 1;
                    eprintln!("FIXTURE_DRIFT [{label}]");
                    for d in &diffs {
                        eprintln!("    {d}");
                    }
                }
            }
            if update && changed {
                let mut out = serde_json::to_string_pretty(&cases).expect("serialize fixtures");
                out.push('\n');
                std::fs::write(&path, out).expect("write fixture file");
                eprintln!("REBLESSED {name}");
            }
        }
        if !update && drift_total > 0 {
            eprintln!(
                "{drift_total} case(s) drifted - re-bless with \
                 UPDATE_FIXTURES=1 cargo test --lib regenerate_stale_fixtures -- --ignored"
            );
        }
    }
}
