//! AUTO-GENERATED by scripts/gen_spec_constants.ts - DO NOT EDIT BY HAND.
//!
//! Source of truth: the `specConstants` blocks in
//! src/pages/referenceContent.ts. Regenerate with
//! `npm run gen:spec-constants` after editing a magnitude. Reference
//! tests read these constants instead of duplicating the number, so a
//! spec change forces the bound test to move with it.

#![allow(dead_code)]

/// status_acid_rain: "deals 3% max HP damage"
pub const ACID_RAIN_DOT_PCT_MAX_HP: f64 = 3.0_f64;

/// ability_adrenaline: "base cooldown is 90 seconds"
pub const ADRENALINE_COOLDOWN_SEC: f64 = 90.0_f64;

/// ability_adrenaline: "Adrenaline lasts for 30 seconds"
pub const ADRENALINE_DURATION_SEC: f64 = 30.0_f64;

/// status_aftershock: "outgoing melee damage by 20%"
pub const AFTERSHOCK_OUTGOING_DAMAGE_REDUCTION_PCT: f64 = 20.0_f64;

/// status_aggressive: "Default duration is 10 seconds"
pub const AGGRESSIVE_DURATION_SEC: f64 = 10.0_f64;

/// status_aggressive: "The emote grants 10 stacks"
pub const AGGRESSIVE_MAX_STACKS: f64 = 10.0_f64;

/// status_aggressive: "by 25% multiplicatively while active"
pub const AGGRESSIVE_OUTGOING_DAMAGE_INCREASE_PCT: f64 = 25.0_f64;

/// compare_use_hunger_rules: "1 appetite unit every 36 seconds"
pub const APPETITE_DRAIN_SEC_PER_UNIT: f64 = 36.0_f64;

/// status_bad_omen: "reduces passive health regeneration by 25%"
pub const BAD_OMEN_REGEN_REDUCTION_PCT: f64 = 25.0_f64;

/// ability_berserk: "bite cooldown is multiplied by 0.5"
pub const BERSERK_BITE_COOLDOWN_MULTIPLIER: f64 = 0.5_f64;

/// ability_berserk: "HP drops below 20%"
pub const BERSERK_HP_GATE_PCT: f64 = 20.0_f64;

/// status_bleed: "2 flat damage per stack on each tick"
pub const BLEED_DAMAGE_PER_STACK_PER_TICK: f64 = 2.0_f64;

/// status_blessings_boon: "restores 3% max HP"
pub const BLESSINGS_BOON_HEAL_PCT_MAX_HP: f64 = 3.0_f64;

/// status_burn: "0.025% max HP base"
pub const BURN_DOT_BASE_PCT_MAX_HP: f64 = 0.025_f64;

/// status_burn: "0.1% per remaining stack"
pub const BURN_DOT_PER_STACK_PCT_MAX_HP: f64 = 0.1_f64;

/// ability_cause_fear: "120 second cooldown"
pub const CAUSE_FEAR_COOLDOWN_SEC: f64 = 120.0_f64;

/// ability_cause_fear: "applies 10 stacks of Fear"
pub const CAUSE_FEAR_STACKS: f64 = 10.0_f64;

/// status_corrosion: "deals 0.5% max HP damage"
pub const CORROSION_DOT_PCT_MAX_HP: f64 = 0.5_f64;

/// status_corrosion: "stops stacking at 90 stacks"
pub const CORROSION_MAX_STACKS: f64 = 90.0_f64;

/// status_corrosion: "starts at 7.5%"
pub const CORROSION_WEIGHT_REDUCTION_BASE_PCT: f64 = 7.5_f64;

/// status_corrosion: "capped at 97.5%"
pub const CORROSION_WEIGHT_REDUCTION_CAP_PCT: f64 = 97.5_f64;

/// status_corrosion: "increases by 1% per stack"
pub const CORROSION_WEIGHT_REDUCTION_PER_STACK_PCT: f64 = 1.0_f64;

/// ability_crystal_breath: "× 0.5 × 1.0 × (1 - breath resistance)"
pub const CRYSTAL_BREATH_CRIT_MULTIPLIER: f64 = 1.0_f64;

/// ability_crystal_breath: "/ 100) × 0.5 × 1.0 ×"
pub const CRYSTAL_BREATH_PER_HIT_MULTIPLIER: f64 = 0.5_f64;

/// ability_cursed_sigil: "85 second cooldown"
pub const CURSED_SIGIL_COOLDOWN_SEC: f64 = 85.0_f64;

/// status_disease: "reduces natural health regeneration by 25%"
pub const DISEASE_REGEN_REDUCTION_PCT: f64 = 25.0_f64;

/// ability_divination: "arms 3 bite charges"
pub const DIVINATION_BITE_CHARGES: f64 = 3.0_f64;

/// ability_divination: "applies 2 stacks of Burn"
pub const DIVINATION_BURN_STACKS: f64 = 2.0_f64;

/// ability_divination: "120 second cooldown"
pub const DIVINATION_COOLDOWN_SEC: f64 = 120.0_f64;

/// ability_divination: "adds +50 flat damage"
pub const DIVINATION_FLAT_DAMAGE: f64 = 50.0_f64;

/// ability_drowsy_area: "60 second cooldown"
pub const DROWSY_AREA_COOLDOWN_SEC: f64 = 60.0_f64;

/// ability_drowsy_area: "applies 5 stacks of Drowsy"
pub const DROWSY_AREA_STACKS: f64 = 5.0_f64;

/// status_drowsy: "increases bite cooldown by 35%"
pub const DROWSY_BITE_COOLDOWN_INCREASE_PCT: f64 = 35.0_f64;

/// status_fear: "reduces outgoing melee damage by 45%"
pub const FEAR_OUTGOING_DAMAGE_REDUCTION_PCT: f64 = 45.0_f64;

/// ability_fire_breath: "× 0.5 × 1.125 × (1 - breath resistance)"
pub const FIRE_BREATH_CRIT_MULTIPLIER: f64 = 1.125_f64;

/// ability_fire_breath: "/ 100) × 0.5 × 1.125 ×"
pub const FIRE_BREATH_PER_HIT_MULTIPLIER: f64 = 0.5_f64;

/// ability_first_strike: "at or above 75%"
pub const FIRST_STRIKE_HP_GATE_PCT: f64 = 75.0_f64;

/// ability_fortify: "90 second cooldown"
pub const FORTIFY_COOLDOWN_SEC: f64 = 90.0_f64;

/// ability_frost_nova: "60 second cooldown"
pub const FROST_NOVA_COOLDOWN_SEC: f64 = 60.0_f64;

/// ability_frost_nova: "lasts for 15 seconds"
pub const FROST_NOVA_DURATION_SEC: f64 = 15.0_f64;

/// ability_frost_nova: "applies 3 stacks of Frostbite"
pub const FROST_NOVA_FROSTBITE_STACKS: f64 = 3.0_f64;

/// ability_frost_snare: "205 second cooldown"
pub const FROST_SNARE_COOLDOWN_SEC: f64 = 205.0_f64;

/// ability_frost_snare: "applies 5 stacks of Frostbite"
pub const FROST_SNARE_FROSTBITE_STACKS: f64 = 5.0_f64;

/// status_frostbite: "increases bite cooldown by 2.5% per stack"
pub const FROSTBITE_BITE_COOLDOWN_INCREASE_PCT_PER_STACK: f64 = 2.5_f64;

/// ability_gold_breath: "× 0.25 × 1.0 × (1 - breath resistance)"
pub const GOLD_BREATH_CRIT_MULTIPLIER: f64 = 1.0_f64;

/// ability_gold_breath: "/ 100) × 0.25 × 1.0 ×"
pub const GOLD_BREATH_PER_HIT_MULTIPLIER: f64 = 0.25_f64;

/// compare_gore_charge: "applies 2 stacks of Bleed"
pub const GORE_CHARGE_BLEED_STACKS: f64 = 2.0_f64;

/// compare_gore_charge: "9 stacks of Deep Wounds"
pub const GORE_CHARGE_DEEP_WOUNDS_STACKS: f64 = 9.0_f64;

/// compare_use_hunger_rules: "overfilled meter 2x faster"
pub const GOURMANDIZER_OVERFILL_DRAIN_MULTIPLIER: f64 = 2.0_f64;

/// ability_green_fire_breath: "× 0.5 × 1.125 × (1 - breath resistance)"
pub const GREEN_FIRE_BREATH_CRIT_MULTIPLIER: f64 = 1.125_f64;

/// ability_green_fire_breath: "/ 100) × 0.5 × 1.125 ×"
pub const GREEN_FIRE_BREATH_PER_HIT_MULTIPLIER: f64 = 0.5_f64;

/// ability_grim_lariat: "60 second cooldown"
pub const GRIM_LARIAT_COOLDOWN_SEC: f64 = 60.0_f64;

/// ability_grim_lariat: "50% of the user's current damage"
pub const GRIM_LARIAT_DAMAGE_PCT_USER_DAMAGE: f64 = 50.0_f64;

/// ability_grim_lariat: "applies 8 stacks of Heartbroken"
pub const GRIM_LARIAT_HEARTBROKEN_STACKS: f64 = 8.0_f64;

/// status_guardians_seal: "reduces incoming damage by 85%"
pub const GUARDIAN_SEAL_DAMAGE_REDUCTION_PCT: f64 = 85.0_f64;

/// status_guardians_seal: "seal holds at most 3 stacks"
pub const GUARDIAN_SEAL_MAX_STACKS: f64 = 3.0_f64;

/// ability_guardians_passage: "300 second cooldown"
pub const GUARDIANS_PASSAGE_COOLDOWN_SEC: f64 = 300.0_f64;

/// ability_guardians_passage: "applies 3 stacks of Guardian's Seal"
pub const GUARDIANS_PASSAGE_SEAL_STACKS: f64 = 3.0_f64;

/// ability_guilt: "reduces incoming damage by 50%"
pub const GUILT_INCOMING_DAMAGE_REDUCTION_PCT: f64 = 50.0_f64;

/// ability_harden: "base cooldown is 120 seconds"
pub const HARDEN_COOLDOWN_SEC: f64 = 120.0_f64;

/// ability_harden: "lasts for 30 seconds"
pub const HARDEN_DURATION_SEC: f64 = 30.0_f64;

/// ability_harden: "effective combat weight is multiplied by 1.35"
pub const HARDEN_WEIGHT_BONUS_MULTIPLIER: f64 = 1.35_f64;

/// ability_haunt_breath: "× 0.75 × 1.175 × (1 - breath resistance)"
pub const HAUNT_BREATH_CRIT_MULTIPLIER: f64 = 1.175_f64;

/// ability_haunt_breath: "/ 100) × 0.75 × 1.175 ×"
pub const HAUNT_BREATH_PER_HIT_MULTIPLIER: f64 = 0.75_f64;

/// status_healing_ailment: "restores 7% of the target's max HP"
pub const HEALING_AILMENT_HEAL_PCT_MAX_HP: f64 = 7.0_f64;

/// status_healing_ailment: "every 15 seconds"
pub const HEALING_AILMENT_TICK_SEC: f64 = 15.0_f64;

/// compare_healing_pulse: "every 90 seconds of cooldown"
pub const HEALING_PULSE_COOLDOWN_SEC: f64 = 90.0_f64;

/// status_heat_wave: "deals 1% max HP damage"
pub const HEAT_WAVE_DOT_PCT_MAX_HP: f64 = 1.0_f64;

/// ability_heliolyths_judgement: "1.6% of the target's max HP"
pub const HELIOLYTHS_JUDGEMENT_PCT_MAX_HP: f64 = 1.6_f64;

/// ability_hunters_curse: "melee damage is multiplied by 2"
pub const HUNTERS_CURSE_BITE_MULTIPLIER: f64 = 2.0_f64;

/// ability_hunters_curse: "120 second cooldown"
pub const HUNTERS_CURSE_COOLDOWN_SEC: f64 = 120.0_f64;

/// ability_hunters_curse: "lasts for 30 seconds"
pub const HUNTERS_CURSE_DURATION_SEC: f64 = 30.0_f64;

/// ability_hunters_curse: "loses 50% of its max HP"
pub const HUNTERS_CURSE_HP_COST_PCT: f64 = 50.0_f64;

/// status_hypothermia: "deals 0.75% max HP damage"
pub const HYPOTHERMIA_DOT_PCT_MAX_HP: f64 = 0.75_f64;

/// ability_ice_breath: "× 0.5 × 1.0 × (1 - breath resistance)"
pub const ICE_BREATH_CRIT_MULTIPLIER: f64 = 1.0_f64;

/// ability_ice_breath: "/ 100) × 0.5 × 1.0 ×"
pub const ICE_BREATH_PER_HIT_MULTIPLIER: f64 = 0.5_f64;

/// ability_lance: "60 second cooldown"
pub const LANCE_COOLDOWN_SEC: f64 = 60.0_f64;

/// ability_lance: "impact hit for 5% of the target's max HP"
pub const LANCE_PRIMARY_PCT_MAX_HP: f64 = 5.0_f64;

/// ability_lance: "deals 1% of the target's max HP"
pub const LANCE_SECONDARY_PCT_MAX_HP: f64 = 1.0_f64;

/// ability_lich_mark: "30 second cooldown"
pub const LICH_MARK_COOLDOWN_SEC: f64 = 30.0_f64;

/// ability_life_leech: "lasts for 12 seconds"
pub const LIFE_LEECH_DURATION_SEC: f64 = 12.0_f64;

/// ability_lightning_breath: "× 1.5 × 1.25 × chain multiplier ×"
pub const LIGHTNING_BREATH_CRIT_MULTIPLIER: f64 = 1.25_f64;

/// ability_lightning_breath: "/ 100) × 1.5 × 1.25 ×"
pub const LIGHTNING_BREATH_PER_HIT_MULTIPLIER: f64 = 1.5_f64;

/// status_malices_mark: "reduces outgoing melee damage by 15%"
pub const MALICES_MARK_OUTGOING_DAMAGE_REDUCTION_PCT: f64 = 15.0_f64;

/// ability_miasma_breath: "× 0.25 × 1.125 × (1 - breath resistance)"
pub const MIASMA_BREATH_CRIT_MULTIPLIER: f64 = 1.125_f64;

/// ability_miasma_breath: "/ 100) × 0.25 × 1.125 ×"
pub const MIASMA_BREATH_PER_HIT_MULTIPLIER: f64 = 0.25_f64;

/// status_natural_regeneration: "ticks every 15 seconds"
pub const NATURAL_REGEN_INTERVAL_SEC: f64 = 15.0_f64;

/// ability_plague_breath: "× 0.25 × 1.125 × (1 - breath resistance)"
pub const PLAGUE_BREATH_CRIT_MULTIPLIER: f64 = 1.125_f64;

/// ability_plague_breath: "/ 100) × 0.25 × 1.125 ×"
pub const PLAGUE_BREATH_PER_HIT_MULTIPLIER: f64 = 0.25_f64;

/// ability_plague_trail: "applies 2 stacks of Disease"
pub const PLAGUE_TRAIL_DISEASE_STACKS: f64 = 2.0_f64;

/// ability_plasma_beam: "× 0.5 × 1.175 × (1 - breath resistance)"
pub const PLASMA_BEAM_CRIT_MULTIPLIER: f64 = 1.175_f64;

/// ability_plasma_beam: "/ 100) × 2.0 × 0.5 × 1.175 ×"
pub const PLASMA_BEAM_PER_HIT_MULTIPLIER: f64 = 2.0_f64;

/// compare_poison_area: "15 second cooldown"
pub const POISON_AREA_COOLDOWN_SEC: f64 = 15.0_f64;

/// compare_poison_area: "applies 5 stacks of Poison"
pub const POISON_AREA_STACKS: f64 = 5.0_f64;

/// status_poison: "starts at 0.2% max HP"
pub const POISON_DOT_BASE_PCT_MAX_HP: f64 = 0.2_f64;

/// status_poison: "increases by 0.05% per stack"
pub const POISON_DOT_PER_STACK_PCT_MAX_HP: f64 = 0.05_f64;

/// compare_power_charge: "gains +50% damage"
pub const POWER_CHARGE_FIRST_HIT_DAMAGE_PCT: f64 = 50.0_f64;

/// compare_power_charge: "applies 2 stacks of Shredded Wings"
pub const POWER_CHARGE_SHREDDED_WINGS_STACKS: f64 = 2.0_f64;

/// ability_quick_recovery: "below 40% HP"
pub const QUICK_RECOVERY_HP_GATE_PCT: f64 = 40.0_f64;

/// ability_quick_recovery: "2x at 0% HP"
pub const QUICK_RECOVERY_MAX_MULTIPLIER: f64 = 2.0_f64;

/// status_radiation: "0.5% max HP damage per tick"
pub const RADIATION_DOT_PCT_MAX_HP: f64 = 0.5_f64;

/// ability_reflect: "45 second cooldown"
pub const REFLECT_COOLDOWN_SEC: f64 = 45.0_f64;

/// ability_reflect: "lasts for 6 seconds"
pub const REFLECT_DURATION_SEC: f64 = 6.0_f64;

/// ability_reflux: "120 second cooldown"
pub const REFLUX_COOLDOWN_SEC: f64 = 120.0_f64;

/// ability_reflux: "5% of the target's max HP"
pub const REFLUX_PRIMARY_PCT_MAX_HP: f64 = 5.0_f64;

/// ability_reflux: "deals direct damage equal to 1.5% of the target's max HP"
pub const REFLUX_SECONDARY_PCT_MAX_HP: f64 = 1.5_f64;

/// ability_rewind: "100 second cooldown"
pub const REWIND_COOLDOWN_SEC: f64 = 100.0_f64;

/// ability_rewind: "capped at 25% of the user's max HP"
pub const REWIND_HEAL_CAP_PCT_MAX_HP: f64 = 25.0_f64;

/// ability_rock_breath: "× 1.0 × 1.05 × (1 - breath resistance)"
pub const ROCK_BREATH_CRIT_MULTIPLIER: f64 = 1.05_f64;

/// ability_rock_breath: "/ 100) × 1.0 × 1.05 ×"
pub const ROCK_BREATH_PER_HIT_MULTIPLIER: f64 = 1.0_f64;

/// ability_sand_breath: "× 0.25 × 1.0 × (1 - breath resistance)"
pub const SAND_BREATH_CRIT_MULTIPLIER: f64 = 1.0_f64;

/// ability_sand_breath: "/ 100) × 0.25 × 1.0 ×"
pub const SAND_BREATH_PER_HIT_MULTIPLIER: f64 = 0.25_f64;

/// status_scared: "Default duration is 10 seconds"
pub const SCARED_DURATION_SEC: f64 = 10.0_f64;

/// status_scared: "The emote grants 10 stacks"
pub const SCARED_MAX_STACKS: f64 = 10.0_f64;

/// status_scared: "reduces outgoing melee damage by 50%"
pub const SCARED_OUTGOING_DAMAGE_REDUCTION_PCT: f64 = 50.0_f64;

/// ability_self_destruct: "capped down to 15% of max HP"
pub const SELF_DESTRUCT_CAP_PCT: f64 = 15.0_f64;

/// ability_self_destruct: "300 second cooldown"
pub const SELF_DESTRUCT_COOLDOWN_SEC: f64 = 300.0_f64;

/// ability_self_destruct: "deals 10% of the target's max HP"
pub const SELF_DESTRUCT_DAMAGE_PCT_MAX_HP: f64 = 10.0_f64;

/// ability_shadow_barrage: "30 second cooldown"
pub const SHADOW_BARRAGE_COOLDOWN_SEC: f64 = 30.0_f64;

/// status_sickly: "reduces passive health regen by 20%"
pub const SICKLY_REGEN_REDUCTION_PCT: f64 = 20.0_f64;

/// ability_solar_beam: "× 1.5 × 1.0 × (1 - breath resistance)"
pub const SOLAR_BEAM_CRIT_MULTIPLIER: f64 = 1.0_f64;

/// ability_solar_beam: "/ 100) × 1.5 × 1.0 ×"
pub const SOLAR_BEAM_PER_HIT_MULTIPLIER: f64 = 1.5_f64;

/// ability_spirit_glare: "× 1.0 × 1.0 × (1 - breath resistance)"
pub const SPIRIT_GLARE_CRIT_MULTIPLIER: f64 = 1.0_f64;

/// ability_spirit_glare: "/ 100) × 1.0 × 1.0 ×"
pub const SPIRIT_GLARE_PER_HIT_MULTIPLIER: f64 = 1.0_f64;

/// ability_spite: "20 second cooldown"
pub const SPITE_COOLDOWN_SEC: f64 = 20.0_f64;

/// compare_use_hunger_rules: "0.5% of max health per stack"
pub const STARVING_DAMAGE_PCT_MAX_HP: f64 = 0.5_f64;

/// status_sticky_teeth: "increases bite cooldown by 65%"
pub const STICKY_TEETH_BITE_COOLDOWN_INCREASE_PCT: f64 = 65.0_f64;

/// ability_storm_breath: "× 0.01 × 1.0 × (1 - breath resistance)"
pub const STORM_BREATH_CRIT_MULTIPLIER: f64 = 1.0_f64;

/// ability_storm_breath: "/ 100) × 0.01 × 1.0 ×"
pub const STORM_BREATH_PER_HIT_MULTIPLIER: f64 = 0.01_f64;

/// compare_storming: "takes 10% more damage"
pub const STORMING_INCOMING_DAMAGE_INCREASE_PCT: f64 = 10.0_f64;

/// ability_thorn_trap: "applies 6 stacks of Bleed"
pub const THORN_TRAP_BLEED_STACKS: f64 = 6.0_f64;

/// ability_thorn_trap: "35 second cooldown"
pub const THORN_TRAP_COOLDOWN_SEC: f64 = 35.0_f64;

/// ability_thorn_trap: "5% of the target's max HP"
pub const THORN_TRAP_DAMAGE_PCT_MAX_HP: f64 = 5.0_f64;

/// ability_thorn_trap: "applies 2 stacks of Freeze"
pub const THORN_TRAP_FREEZE_STACKS: f64 = 2.0_f64;

/// ability_totem: "active for 30 seconds"
pub const TOTEM_ACTIVE_WINDOW_SEC: f64 = 30.0_f64;

/// ability_totem: "180 second cooldown"
pub const TOTEM_COOLDOWN_SEC: f64 = 180.0_f64;

/// ability_toxic_trail: "applies 2 stacks of Poison"
pub const TOXIC_TRAIL_POISON_STACKS: f64 = 2.0_f64;

/// ability_toxic_trap: "75 second cooldown"
pub const TOXIC_TRAP_COOLDOWN_SEC: f64 = 75.0_f64;

/// ability_toxic_trap: "always exactly 25 opponent bites"
pub const TOXIC_TRAP_DURABILITY_BITES: f64 = 25.0_f64;

/// ability_toxic_trap: "receives 5 stacks of Poison"
pub const TOXIC_TRAP_POISON_STACKS: f64 = 5.0_f64;

/// ability_toxin_breath: "× 0.25 × 1.025 × (1 - breath resistance)"
pub const TOXIN_BREATH_CRIT_MULTIPLIER: f64 = 1.025_f64;

/// ability_toxin_breath: "/ 100) × 0.25 × 1.025 ×"
pub const TOXIN_BREATH_PER_HIT_MULTIPLIER: f64 = 0.25_f64;

/// ability_two_faced: "Madness multiplies damage by 0.625"
pub const TWO_FACED_MADNESS_MULTIPLIER: f64 = 0.625_f64;

/// ability_two_faced: "Tranquility multiplies damage by 1.6"
pub const TWO_FACED_TRANQUILITY_MULTIPLIER: f64 = 1.6_f64;

/// ability_unbridled_rage: "120 second cooldown"
pub const UNBRIDLED_RAGE_COOLDOWN_SEC: f64 = 120.0_f64;

/// ability_unbridled_rage: "lasts for 30 seconds"
pub const UNBRIDLED_RAGE_DURATION_SEC: f64 = 30.0_f64;

/// ability_virus_breath: "× 0.25 × 1.0 × (1 - breath resistance)"
pub const VIRUS_BREATH_CRIT_MULTIPLIER: f64 = 1.0_f64;

/// ability_virus_breath: "/ 100) × 0.25 × 1.0 ×"
pub const VIRUS_BREATH_PER_HIT_MULTIPLIER: f64 = 0.25_f64;

/// ability_wardens_rage: "reaches 8.5x damage at full strength"
pub const WARDENS_RAGE_CAP_MULTIPLIER: f64 = 8.5_f64;

/// ability_wardens_resistance: "HP is at or below 50%"
pub const WARDENS_RESISTANCE_HP_GATE_PCT: f64 = 50.0_f64;

/// ability_water_breath: "× 0.75 × 1.1 × (1 - breath resistance)"
pub const WATER_BREATH_CRIT_MULTIPLIER: f64 = 1.1_f64;

/// ability_water_breath: "/ 100) × 0.75 × 1.1 ×"
pub const WATER_BREATH_PER_HIT_MULTIPLIER: f64 = 0.75_f64;

/// ability_yolk_bomb: "30 second cooldown"
pub const YOLK_BOMB_COOLDOWN_SEC: f64 = 30.0_f64;
