//! User-defined status spec - engine-level **parametric** status definition
//! (Custom Abilities v2).
//!
//! A built-in status's behaviour is split across a generated metadata
//! registry (`effects_registry.rs`, from `statusCatalog.ts`) plus
//! hand-written per-id formulas in `statuses.rs` / `combat.rs`. User
//! statuses can't add hand-written Rust, so they expose a **curated
//! parametric model** instead: a fixed set of knobs covering the common
//! status archetypes (DoT / HoT, regen modifier, damage / cooldown
//! multipliers, stacking + decay). Anything outside this set stays
//! built-in.
//!
//! Like [`crate::policy::user_ability::UserAbilitySpec`], a status spec is
//! registered once into a process-wide registry (`wasm_api`) under a
//! `user.`-namespaced id and snapshotted on demand by the runtime. The
//! `statuses.rs` metadata seams consult the registry **user-first** (gated
//! on the `user.` id prefix, so built-in ticks pay nothing) and fall back
//! to the generated catalog.
//!
//! The spec is pure data: no per-tick code, no allocation beyond the
//! parsed struct. Behaviour is derived from the knobs via the helper
//! methods (`dot_damage`, `tick_heal_amount`, `periodic_tick_sec`).

use serde::{Deserialize, Serialize};

use crate::effects::EffectBatch;
use crate::policy::user_ability::{Expr, TickTrigger};

/// Sign / cleanse-eligibility hint, mirroring `effects_registry::Polarity`
/// but owned by the spec so its serde shape is independent of the
/// generated registry (which is regenerated by `npm run gen:registry`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum UserStatusPolarity {
    Positive,
    #[default]
    Negative,
    Neutral,
}

/// Stack-composition rule. `Stacking` adds, `NonStacking` refreshes a
/// single application, `Unique` is a one-shot singleton.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum UserStatusStackRule {
    #[default]
    Stacking,
    NonStacking,
    Unique,
}

/// Periodic-tick behaviour. `Flat` amounts are raw HP; `PctMaxHp` amounts
/// are percentage-points of the bearer's max HP (so `tick_base = 0.2`,
/// `tick_per_stack = 0.05` reproduces Poison's `(0.2 + 0.05·stacks)%`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum UserStatusTickKind {
    #[default]
    None,
    DotFlat,
    DotPctMaxHp,
    HealFlat,
    HealPctMaxHp,
}

impl UserStatusTickKind {
    fn is_heal(self) -> bool {
        matches!(self, UserStatusTickKind::HealFlat | UserStatusTickKind::HealPctMaxHp)
    }
    fn is_dot(self) -> bool {
        matches!(self, UserStatusTickKind::DotFlat | UserStatusTickKind::DotPctMaxHp)
    }
    fn is_pct(self) -> bool {
        matches!(
            self,
            UserStatusTickKind::DotPctMaxHp | UserStatusTickKind::HealPctMaxHp
        )
    }
}

/// A user-authored status definition. Default-everything where sensible
/// so a minimal spec (`id` + `display_name`) is a valid inert marker.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct UserStatusSpec {
    /// Schema version. Default `1`. Future migrations bump this.
    #[serde(default = "default_status_version")]
    pub version: u32,
    /// Stable id, must start with `user.` (namespace convention shared
    /// with user abilities / timings) so it never shadows a built-in
    /// catalog id and the runtime can cheaply gate on the prefix.
    pub id: String,
    /// Display name for combat-log / UI.
    pub display_name: String,
    /// Sign hint (UI colour, Yolk-Bomb routing parity). Default negative.
    #[serde(default)]
    pub polarity: UserStatusPolarity,
    /// Stack composition rule. Default stacking.
    #[serde(default)]
    pub stack_rule: UserStatusStackRule,
    /// Stack cap. `None` (default) = unbounded.
    #[serde(default)]
    pub max_stacks: Option<f64>,
    /// Seconds for one stack to decay off. Default 3.0 (engine baseline).
    #[serde(default = "default_decay_interval_sec")]
    pub decay_interval_sec: f64,
    /// Periodic-tick behaviour. Default `None` (no DoT/HoT).
    #[serde(default)]
    pub tick_kind: UserStatusTickKind,
    /// Flat / pct base amount applied once per tick regardless of stacks.
    #[serde(default)]
    pub tick_base: f64,
    /// Additional flat / pct amount per stack per tick.
    #[serde(default)]
    pub tick_per_stack: f64,
    /// Seconds between ticks. `<= 0` (default) = no periodic tick even if
    /// `tick_kind` is set.
    #[serde(default)]
    pub tick_interval_sec: f64,
    /// Flat additive HP-regen percentage modifier while present
    /// (e.g. `-100.0` blocks regen, `+20.0` boosts it).
    #[serde(default)]
    pub regen_mod_pct: f64,
    /// Per-stack additive HP-regen percentage modifier.
    #[serde(default)]
    pub regen_mod_per_stack_pct: f64,
    /// Multiplier on damage the bearer TAKES (1.0 = neutral, 1.5 =
    /// +50% incoming). Phase-6 modifier seam.
    #[serde(default = "default_mult")]
    pub incoming_damage_mult: f64,
    /// Multiplier on damage the bearer DEALS (1.0 = neutral, 0.5 =
    /// −50% outgoing).
    #[serde(default = "default_mult")]
    pub outgoing_damage_mult: f64,
    /// Multiplier on the bearer's bite cooldown (1.0 = neutral, 0.8 =
    /// 20% faster bites).
    #[serde(default = "default_mult")]
    pub bite_cooldown_mult: f64,

    // Cleanse-eligibility is NOT a field: Fortify-removability is derived from
    // `polarity` (negative → removable), unified with built-in statuses - see
    // `statuses::is_fortify_removable_status`.

    // ── Programmable extensions (Custom Abilities v2 Phase 8.x). All
    //    optional; a spec with none of these is a pure parametric status and
    //    behaves byte-for-byte as before - the runtime gates the whole
    //    hook / Expr path on [`Self::has_dynamic`] and never builds an
    //    `EffectContext` for a parametric-only status. Behaviour belongs to
    //    the status and rides with it onto any bearer: hooks fire with the
    //    bearer as caster (frame: self = bearer, opponent = other side), and
    //    any stat modifier a hook installs is torn down when the status
    //    leaves the creature.

    /// Fired once when the status first appears on a creature (the status
    /// key transitions absent → present). Does NOT re-fire on restack - use
    /// Expr scalars reading `status.stacks` for per-stack scaling.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_apply: Option<EffectBatch>,
    /// Fired once when the status leaves the creature (decay to zero,
    /// Fortify cleanse, or explicit clear). After it fires, every stat
    /// modifier the status installed via its hooks is stripped and HP is
    /// reconciled **proportionally** (the HP fraction is preserved across the
    /// max-HP change - FormSwap's `ratio` revert). Custom HP handling on
    /// expiry is authored as `on_expire` effects, not a knob.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_expire: Option<EffectBatch>,
    /// Periodic hook fired on its own cadence while present. Reuses the
    /// ability [`TickTrigger`] shape (`interval_sec` + `EffectBatch`); the
    /// engine clamps the interval to `MIN_TICK_INTERVAL_SEC` at dispatch.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_tick: Option<TickTrigger>,

    // ── Bearer-reactive triggers (Phase 9.x - status↔ability parity). These
    //    mirror the bearer-meaningful subset of the ability `TriggerHook`
    //    surface: they fire when the *bearer* experiences a combat event, with
    //    the bearer as `self` / the other side as `opponent`, sharing the exact
    //    per-iteration diffs/deltas the ability triggers already consume in
    //    phase 16. Each carries `event.<key>` context (e.g. `event.damage_taken`,
    //    `event.heal_amount`) resolvable inside the batch's Exprs.
    //
    //    NOTE the lifecycle hooks above are about THIS status (`on_apply` =
    //    this status appeared); `on_status_apply` / `on_status_expire` below are
    //    REACTIVE to *another* status arriving/leaving the bearer (mirror of the
    //    ability hooks of the same name).

    /// Fired once at t=0 for a status present at fight start (bearer = self).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_round_start: Option<EffectBatch>,
    /// Fired when the bearer took damage this iteration. `event.damage_taken`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_take_damage: Option<EffectBatch>,
    /// Fired when the bearer dealt damage this iteration. `event.damage_dealt`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_deal_damage: Option<EffectBatch>,
    /// Fired when the bearer killed the opponent this iteration.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_kill: Option<EffectBatch>,
    /// Fired when the bearer's first-strike state changed.
    /// `event.first_strike_active` (1.0 / 0.0).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_first_strike: Option<EffectBatch>,
    /// Fired when the bearer received healing this iteration. `event.heal_amount`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_heal: Option<EffectBatch>,
    /// Fired when ANOTHER status was applied to the bearer this iteration.
    /// `event.applied_status_count` + `event.applied.<id>` (1.0 each).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_status_apply: Option<EffectBatch>,
    /// Fired when ANOTHER status left the bearer this iteration.
    /// `event.expired_status_count` + `event.expired.<id>` (1.0 each).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_status_expire: Option<EffectBatch>,
    /// Pre-mitigation hook before the bearer TAKES damage (shield/absorb). The
    /// batch may write `set_extra self damage_override = N` to replace the final
    /// amount. `event.raw_damage` / `event.damage_taken` / `event.prevented_damage`
    /// / `event.is_bite` / `event.is_breath` / `event.is_dot`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_before_take_damage: Option<EffectBatch>,
    /// Pre-mitigation hook before the bearer DEALS damage (amp). Same event
    /// surface as `on_before_take_damage`; override applies before the victim's.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_before_deal_damage: Option<EffectBatch>,
    /// Fired when this status loses stacks while SURVIVING (natural decay,
    /// partial Fortify cleanse, ModifyStatusStacks < 0) - i.e. stack count
    /// dropped this iteration but did not reach 0 (a drop to 0 is `on_expire`).
    /// `event.stacks_lost` = the decrease. Status-specific (no ability twin).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_decay: Option<EffectBatch>,
    /// Fired when this already-present status gains stacks (re-applied /
    /// refreshed) - the absent→present case is `on_apply`, not this.
    /// `event.stacks_gained` = the increase.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_restack: Option<EffectBatch>,

    // ── Expr overrides for the parametric numeric knobs. When present, the
    //    loop-level resolver evaluates the Expr (over `status.stacks`,
    //    `status.max_hp`, `time`, `self.*`) each iteration and the consuming
    //    seam uses the resolved value in place of the static knob above.
    //    `None` ⇒ the static f64 is used (byte-identical). Additive overrides
    //    rather than retyping the knobs keeps zero-Expr specs untouched.

    /// Overrides the combined per-tick DoT/HoT magnitude (otherwise
    /// `tick_base + tick_per_stack·stacks`, still scaled to max-hp for the
    /// `*PctMaxHp` kinds) when set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tick_amount_expr: Option<Expr>,
    /// Overrides `incoming_damage_mult` when set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub incoming_damage_mult_expr: Option<Expr>,
    /// Overrides `outgoing_damage_mult` when set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub outgoing_damage_mult_expr: Option<Expr>,
    /// Overrides `bite_cooldown_mult` when set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bite_cooldown_mult_expr: Option<Expr>,
    /// Overrides the combined regen modifier (otherwise
    /// `regen_mod_total_pct`) when set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub regen_mod_expr: Option<Expr>,
}

fn default_status_version() -> u32 {
    1
}
fn default_decay_interval_sec() -> f64 {
    3.0
}
fn default_mult() -> f64 {
    1.0
}

impl UserStatusSpec {
    /// Tick period if this status ticks, else `None`. Mirrors the
    /// `status_tick_sec` contract (`None` ⇒ no scheduler entry).
    pub fn periodic_tick_sec(&self) -> Option<f64> {
        if self.tick_interval_sec > 0.0 && self.tick_kind != UserStatusTickKind::None {
            Some(self.tick_interval_sec)
        } else {
            None
        }
    }

    /// Raw per-tick magnitude (`base + per_stack·stacks`, scaled to max-hp
    /// for the `PctMaxHp` kinds). Sign-agnostic - callers route via
    /// [`Self::dot_damage`] / [`Self::tick_heal_amount`].
    fn tick_amount(&self, max_hp: f64, stacks: f64) -> f64 {
        let coeff = self.tick_base + self.tick_per_stack * stacks.max(0.0);
        if self.tick_kind.is_pct() {
            coeff * max_hp / 100.0
        } else {
            coeff
        }
    }

    /// DoT damage this tick (0 unless `tick_kind` is a DoT variant).
    pub fn dot_damage(&self, max_hp: f64, stacks: f64) -> f64 {
        if self.tick_kind.is_dot() {
            self.tick_amount(max_hp, stacks).max(0.0)
        } else {
            0.0
        }
    }

    /// HoT heal this tick (0 unless `tick_kind` is a heal variant).
    pub fn tick_heal_amount(&self, max_hp: f64, stacks: f64) -> f64 {
        if self.tick_kind.is_heal() {
            self.tick_amount(max_hp, stacks).max(0.0)
        } else {
            0.0
        }
    }

    /// Per-tick magnitude from an explicit coefficient (an Expr-resolved
    /// `tick_amount_expr` value) in place of `tick_base + tick_per_stack·stacks`.
    /// Pct-kinds still scale to max-hp, so the same authoring intent holds.
    fn tick_amount_from_coeff(&self, max_hp: f64, coeff: f64) -> f64 {
        if self.tick_kind.is_pct() {
            coeff * max_hp / 100.0
        } else {
            coeff
        }
    }

    /// DoT damage from an Expr-resolved coefficient (0 unless a DoT kind).
    pub fn dot_damage_from_coeff(&self, max_hp: f64, coeff: f64) -> f64 {
        if self.tick_kind.is_dot() {
            self.tick_amount_from_coeff(max_hp, coeff).max(0.0)
        } else {
            0.0
        }
    }

    /// HoT heal from an Expr-resolved coefficient (0 unless a heal kind).
    pub fn tick_heal_amount_from_coeff(&self, max_hp: f64, coeff: f64) -> f64 {
        if self.tick_kind.is_heal() {
            self.tick_amount_from_coeff(max_hp, coeff).max(0.0)
        } else {
            0.0
        }
    }

    /// Combined HP-regen percentage modifier at `stacks`.
    pub fn regen_mod_total_pct(&self, stacks: f64) -> f64 {
        self.regen_mod_pct + self.regen_mod_per_stack_pct * stacks.max(0.0)
    }

    /// True if any hook is set - the lifecycle trio (`on_apply` / `on_tick` /
    /// `on_expire`) or any bearer-reactive trigger.
    pub fn has_hooks(&self) -> bool {
        self.on_apply.is_some()
            || self.on_tick.is_some()
            || self.on_expire.is_some()
            || self.on_round_start.is_some()
            || self.on_take_damage.is_some()
            || self.on_deal_damage.is_some()
            || self.on_kill.is_some()
            || self.on_first_strike.is_some()
            || self.on_heal.is_some()
            || self.on_status_apply.is_some()
            || self.on_status_expire.is_some()
            || self.on_before_take_damage.is_some()
            || self.on_before_deal_damage.is_some()
            || self.on_decay.is_some()
            || self.on_restack.is_some()
    }

    /// True if any parametric knob is overridden by an Expr.
    pub fn has_expr_scalars(&self) -> bool {
        self.tick_amount_expr.is_some()
            || self.incoming_damage_mult_expr.is_some()
            || self.outgoing_damage_mult_expr.is_some()
            || self.bite_cooldown_mult_expr.is_some()
            || self.regen_mod_expr.is_some()
    }

    /// True if this status carries any programmable behaviour beyond the pure
    /// parametric knobs. The runtime gates the entire hook / Expr-resolve
    /// dispatch on this so a parametric-only (or built-in) status stays
    /// byte-identical and pays only the `user.`-prefix scan.
    pub fn has_dynamic(&self) -> bool {
        self.has_hooks() || self.has_expr_scalars()
    }

    /// Clamp authoring slips into a sane shape. Idempotent. Called at
    /// parse time so the runtime never sees a degenerate spec.
    pub fn normalize(&mut self) {
        if self.version == 0 {
            self.version = 1;
        }
        if !self.decay_interval_sec.is_finite() || self.decay_interval_sec <= 0.0 {
            self.decay_interval_sec = default_decay_interval_sec();
        }
        if !self.tick_interval_sec.is_finite() || self.tick_interval_sec < 0.0 {
            self.tick_interval_sec = 0.0;
        }
        for mult in [
            &mut self.incoming_damage_mult,
            &mut self.outgoing_damage_mult,
            &mut self.bite_cooldown_mult,
        ] {
            if !mult.is_finite() || *mult < 0.0 {
                *mult = default_mult();
            }
        }
        if let Some(cap) = self.max_stacks {
            if !cap.is_finite() || cap <= 0.0 {
                self.max_stacks = None;
            }
        }
        for v in [
            &mut self.tick_base,
            &mut self.tick_per_stack,
            &mut self.regen_mod_pct,
            &mut self.regen_mod_per_stack_pct,
        ] {
            if !v.is_finite() {
                *v = 0.0;
            }
        }
    }

    /// Registration-time sanity check. Mirrors `UserAbilitySpec::validate`
    /// - id namespace + non-empty name. Runtime reads of an unregistered
    /// id are already neutral, so deep validation isn't required here.
    pub fn validate(&self) -> Result<(), StatusSpecError> {
        if self.id.is_empty() {
            return Err(StatusSpecError::IdEmpty);
        }
        if !self.id.starts_with("user.") {
            return Err(StatusSpecError::IdNotUserNamespaced { id: self.id.clone() });
        }
        if self.display_name.trim().is_empty() {
            return Err(StatusSpecError::DisplayNameEmpty);
        }
        Ok(())
    }
}

/// Validation failures surfaced at registration time.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum StatusSpecError {
    IdEmpty,
    IdNotUserNamespaced { id: String },
    DisplayNameEmpty,
}

impl std::fmt::Display for StatusSpecError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            StatusSpecError::IdEmpty => write!(f, "status id must not be empty"),
            StatusSpecError::IdNotUserNamespaced { id } => write!(
                f,
                "status id `{id}` must start with `user.` to register as a custom status"
            ),
            StatusSpecError::DisplayNameEmpty => write!(f, "display_name must not be empty"),
        }
    }
}

impl std::error::Error for StatusSpecError {}

/// Parse + normalize + validate a JSON status spec.
pub fn parse_user_status_spec(json: &str) -> Result<UserStatusSpec, StatusParseError> {
    let mut spec: UserStatusSpec = serde_json::from_str(json).map_err(StatusParseError::Json)?;
    spec.normalize();
    spec.validate().map_err(StatusParseError::Validation)?;
    Ok(spec)
}

#[derive(Debug)]
pub enum StatusParseError {
    Json(serde_json::Error),
    Validation(StatusSpecError),
}

impl std::fmt::Display for StatusParseError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            StatusParseError::Json(e) => write!(f, "invalid JSON: {e}"),
            StatusParseError::Validation(e) => write!(f, "{e}"),
        }
    }
}

impl std::error::Error for StatusParseError {}

#[cfg(test)]
mod tests {
    use super::*;

    fn dot_spec() -> UserStatusSpec {
        parse_user_status_spec(
            r#"{
                "id": "user.Searing",
                "display_name": "Searing",
                "polarity": "negative",
                "tick_kind": "dot_pct_max_hp",
                "tick_base": 0.2,
                "tick_per_stack": 0.05,
                "tick_interval_sec": 3.0,
                "decay_interval_sec": 3.0
            }"#,
        )
        .expect("parse")
    }

    #[test]
    fn parse_defaults_minimal_spec() {
        let spec =
            parse_user_status_spec(r#"{ "id": "user.Mark", "display_name": "Mark" }"#).expect("parse");
        assert_eq!(spec.version, 1);
        assert_eq!(spec.decay_interval_sec, 3.0);
        assert_eq!(spec.incoming_damage_mult, 1.0);
        assert_eq!(spec.outgoing_damage_mult, 1.0);
        assert_eq!(spec.bite_cooldown_mult, 1.0);
        assert_eq!(spec.tick_kind, UserStatusTickKind::None);
        assert_eq!(spec.periodic_tick_sec(), None);
        assert_eq!(spec.dot_damage(10_000.0, 5.0), 0.0);
    }

    #[test]
    fn validate_rejects_bad_id_and_name() {
        assert_eq!(
            parse_user_status_spec(r#"{ "id": "", "display_name": "x" }"#)
                .err()
                .map(|e| matches!(e, StatusParseError::Validation(StatusSpecError::IdEmpty))),
            Some(true)
        );
        assert!(matches!(
            parse_user_status_spec(r#"{ "id": "Searing", "display_name": "x" }"#).err(),
            Some(StatusParseError::Validation(StatusSpecError::IdNotUserNamespaced { .. }))
        ));
        assert!(matches!(
            parse_user_status_spec(r#"{ "id": "user.x", "display_name": "  " }"#).err(),
            Some(StatusParseError::Validation(StatusSpecError::DisplayNameEmpty))
        ));
    }

    #[test]
    fn dot_pct_matches_poison_shape() {
        let spec = dot_spec();
        // (0.2 + 0.05·5)% of 10_000 = 0.45% · 10_000 = 45.
        assert!((spec.dot_damage(10_000.0, 5.0) - 45.0).abs() < 1e-9);
        // Heal accessor is 0 for a DoT.
        assert_eq!(spec.tick_heal_amount(10_000.0, 5.0), 0.0);
        assert_eq!(spec.periodic_tick_sec(), Some(3.0));
    }

    #[test]
    fn heal_flat_and_pct() {
        let flat = parse_user_status_spec(
            r#"{ "id": "user.Mend", "display_name": "Mend", "tick_kind": "heal_flat",
                 "tick_base": 50.0, "tick_per_stack": 10.0, "tick_interval_sec": 2.0 }"#,
        )
        .unwrap();
        assert_eq!(flat.tick_heal_amount(10_000.0, 3.0), 80.0); // 50 + 10·3
        assert_eq!(flat.dot_damage(10_000.0, 3.0), 0.0);

        let pct = parse_user_status_spec(
            r#"{ "id": "user.Bloom", "display_name": "Bloom", "tick_kind": "heal_pct_max_hp",
                 "tick_base": 1.0, "tick_interval_sec": 1.0 }"#,
        )
        .unwrap();
        assert!((pct.tick_heal_amount(10_000.0, 0.0) - 100.0).abs() < 1e-9); // 1% · 10_000
    }

    #[test]
    fn normalize_clamps_degenerate_values() {
        let spec = parse_user_status_spec(
            r#"{ "id": "user.Bad", "display_name": "Bad", "decay_interval_sec": -5.0,
                 "incoming_damage_mult": -2.0, "max_stacks": 0.0, "tick_interval_sec": -1.0 }"#,
        )
        .unwrap();
        assert_eq!(spec.decay_interval_sec, 3.0);
        assert_eq!(spec.incoming_damage_mult, 1.0);
        assert_eq!(spec.max_stacks, None);
        assert_eq!(spec.tick_interval_sec, 0.0);
    }

    #[test]
    fn regen_mod_total_combines_flat_and_per_stack() {
        let spec = parse_user_status_spec(
            r#"{ "id": "user.Wither", "display_name": "Wither", "regen_mod_pct": -20.0,
                 "regen_mod_per_stack_pct": -10.0 }"#,
        )
        .unwrap();
        assert_eq!(spec.regen_mod_total_pct(3.0), -50.0); // -20 + -10·3
    }

    #[test]
    fn parametric_only_spec_is_not_dynamic() {
        // A pure parametric status (the whole pre-Phase-8 population + every
        // built-in) carries no hooks and no Expr overrides → the runtime
        // gate stays false → byte-identical behaviour.
        let spec = dot_spec();
        assert!(!spec.has_hooks());
        assert!(!spec.has_expr_scalars());
        assert!(!spec.has_dynamic());
    }

    #[test]
    fn programmable_status_round_trips_lossless() {
        // The HP-cap acceptance status: on_apply caps max HP, expire restores
        // proportionally; plus an on_tick DoT, an on_expire log effect, and an
        // Expr-overridden incoming-damage multiplier.
        let json = r#"{
            "id": "user.Frail",
            "display_name": "Frail",
            "polarity": "negative",
            "decay_interval_sec": 5.0,
            "incoming_damage_mult": 1.0,
            "incoming_damage_mult_expr": { "kind": "var", "path": "status.stacks" },
            "tick_amount_expr": {
                "kind": "bin", "op": "mul",
                "left": { "kind": "var", "path": "status.stacks" },
                "right": { "kind": "const", "value": 5.0 }
            },
            "on_apply": {
                "name": "Frail in",
                "effects": [
                    { "kind": "form_swap", "target": "caster",
                      "stat_changes": [{ "field": "health", "mode": "mul", "value": 0.3 }],
                      "duration_sec": 0.0, "hp_policy": { "kind": "ratio" } }
                ]
            },
            "on_tick": {
                "interval_sec": 2.0,
                "effects": {
                    "name": "Frail tick",
                    "effects": [{ "kind": "deal_direct_damage", "target": "caster", "amount": 10.0 }]
                }
            },
            "on_expire": {
                "name": "Frail out",
                "effects": [{ "kind": "heal_hp", "target": "caster", "amount": 0.0 }]
            }
        }"#;
        let spec = parse_user_status_spec(json).expect("parse");
        assert!(spec.has_hooks());
        assert!(spec.has_expr_scalars());
        assert!(spec.has_dynamic());
        assert!(spec.on_apply.is_some());
        assert!(spec.on_expire.is_some());
        assert_eq!(spec.on_tick.as_ref().map(|t| t.interval_sec), Some(2.0));

        // Lossless serialize → parse round-trip (the parity contract the
        // TS DSL must also satisfy).
        let reser = serde_json::to_string(&spec).expect("serialize");
        let spec2 = parse_user_status_spec(&reser).expect("re-parse");
        assert_eq!(spec, spec2);
    }

    #[test]
    fn new_fields_absent_from_serialized_parametric_spec() {
        // skip_serializing_if keeps a parametric spec's JSON free of the new
        // keys, so existing snapshots/round-trips are unaffected.
        let spec = dot_spec();
        let json = serde_json::to_string(&spec).unwrap();
        assert!(!json.contains("on_apply"));
        assert!(!json.contains("on_tick"));
        assert!(!json.contains("on_expire"));
        assert!(!json.contains("tick_amount_expr"));
        assert!(!json.contains("expire_hp_policy"));
    }
}
