// TS -> Rust + TS codegen for spec magnitude constants.
//
// Reads the `specConstants` blocks off the Reference entries in
// src/pages/referenceContent.ts and emits the single source of truth
// for every magnitude a reference test checks: a Rust module
// (wasm-engine/src/spec_constants.rs) and a TS module
// (src/engine/specConstants.generated.ts). Reference tests read the
// constant instead of hardcoding the number, so changing the spec prose
// forces the bound test to move with it.
//
// Run: `npm run gen:spec-constants` after editing a `specConstants`
// block. Both generated files are committed; the drift gate
// (src/engine/specConstantsDrift.test.ts) keeps them in sync.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  ABILITY_POLICY_REFERENCE_DRAFTS,
  BATTLE_SETTING_REFERENCE_DRAFTS,
  MODELED_ABILITY_REFERENCE_DRAFTS,
  PLUSHIE_REFERENCE_DRAFTS,
  STATUS_REFERENCE_DRAFTS,
  type SpecConstant,
} from "../src/pages/referenceContent";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, "..");
const RUST_OUT_PATH = path.join(REPO_ROOT, "wasm-engine", "src", "spec_constants.rs");
const TS_OUT_PATH = path.join(REPO_ROOT, "src", "engine", "specConstants.generated.ts");

// Entry arrays that carry `mechanics` (and may carry `specConstants`).
// Approximation drafts use gameTruth/currentApproximation instead of
// mechanics and have no spec constants, so they are excluded.
type SpecConstantEntry = { id: string; mechanics?: string[]; specConstants?: SpecConstant[] };

const ENTRIES: SpecConstantEntry[] = [
  ...MODELED_ABILITY_REFERENCE_DRAFTS,
  ...STATUS_REFERENCE_DRAFTS,
  ...BATTLE_SETTING_REFERENCE_DRAFTS,
  ...ABILITY_POLICY_REFERENCE_DRAFTS,
  ...PLUSHIE_REFERENCE_DRAFTS,
];

type OwnedConstant = SpecConstant & { entryId: string };

// Collect and validate every spec constant. The validation is the weld:
// each constant's `quote` must be a verbatim slice of one of its entry's
// bullets and must contain the value, so the prose and the number cannot
// drift apart without this throwing - which reds the drift gate.
function collectConstants(): OwnedConstant[] {
  const owned: OwnedConstant[] = [];
  const seenKeys = new Map<string, string>();
  for (const entry of ENTRIES) {
    for (const constant of entry.specConstants ?? []) {
      const prior = seenKeys.get(constant.key);
      if (prior) {
        throw new Error(
          `spec constant key "${constant.key}" is defined twice (${prior} and ${entry.id})`,
        );
      }
      seenKeys.set(constant.key, entry.id);

      const bullets = entry.mechanics ?? [];
      if (!bullets.some((bullet) => bullet.includes(constant.quote))) {
        throw new Error(
          `spec constant "${constant.key}" (${entry.id}): quote ${JSON.stringify(constant.quote)} `
          + `is not a substring of any mechanics bullet`,
        );
      }
      if (!constant.quote.includes(String(constant.value))) {
        throw new Error(
          `spec constant "${constant.key}" (${entry.id}): quote ${JSON.stringify(constant.quote)} `
          + `does not contain its value ${constant.value}`,
        );
      }
      owned.push({ ...constant, entryId: entry.id });
    }
  }
  owned.sort((a, b) => a.key.localeCompare(b.key));
  return owned;
}

function f64Literal(value: number): string {
  // Plain integer doubles get an explicit decimal so rustfmt keeps them f64.
  if (Number.isInteger(value)) return `${value}.0_f64`;
  return `${value}_f64`;
}

const RUST_HEADER = `//! AUTO-GENERATED by scripts/gen_spec_constants.ts - DO NOT EDIT BY HAND.
//!
//! Source of truth: the \`specConstants\` blocks in
//! src/pages/referenceContent.ts. Regenerate with
//! \`npm run gen:spec-constants\` after editing a magnitude. Reference
//! tests read these constants instead of duplicating the number, so a
//! spec change forces the bound test to move with it.

#![allow(dead_code)]
`;

// Pure function form - exported so the drift gate (vitest) can re-run the
// codegen logic and compare against the committed file.
export function generateSpecConstantsRustSource(): string {
  const blocks = collectConstants().map((constant) => {
    const name = constant.key.toUpperCase();
    return `/// ${constant.entryId}: "${constant.quote}"\n`
      + `pub const ${name}: f64 = ${f64Literal(constant.value)};`;
  });
  return `${RUST_HEADER}\n${blocks.join("\n\n")}\n`;
}

const TS_HEADER = `// AUTO-GENERATED by scripts/gen_spec_constants.ts - DO NOT EDIT BY HAND.
//
// Source of truth: the \`specConstants\` blocks in
// src/pages/referenceContent.ts. Regenerate with
// \`npm run gen:spec-constants\`. Tests read these instead of duplicating
// spec magnitudes.
`;

export function generateSpecConstantsTsSource(): string {
  const entries = collectConstants().map(
    (constant) => `  /** ${constant.entryId}: "${constant.quote}" */\n  ${constant.key}: ${constant.value},`,
  );
  return `${TS_HEADER}\nexport const SPEC_CONSTANTS = {\n${entries.join("\n")}\n} as const;\n`;
}

export const SPEC_CONSTANTS_RUST_OUT_PATH = RUST_OUT_PATH;
export const SPEC_CONSTANTS_TS_OUT_PATH = TS_OUT_PATH;

// Only run the file-writing side-effect when invoked directly via the
// CLI, not when imported from the drift test.
const invokedDirectly =
  import.meta.url === `file://${process.argv[1]?.replace(/\\/g, "/")}`
  || import.meta.url.endsWith(process.argv[1]?.replace(/\\/g, "/") ?? "");

if (invokedDirectly) {
  fs.writeFileSync(RUST_OUT_PATH, generateSpecConstantsRustSource(), "utf8");
  fs.writeFileSync(TS_OUT_PATH, generateSpecConstantsTsSource(), "utf8");
  console.log(
    `Generated spec_constants.rs + specConstants.generated.ts - ${collectConstants().length} constants.`,
  );
}
