/**
 * Generates `src/shared/shareVocabulary.ts` - the append-only name table
 * that COSM3 share links reference by index.
 *
 * APPEND-ONLY contract: this script reads the existing committed vocabulary
 * (if any), keeps it verbatim, and only appends names not already present.
 * It never reorders or removes entries, because a COSM3 link stores a name
 * as its index here - shifting an index would make old links resolve to the
 * wrong name. Names absent from the table fall back to inline strings at
 * encode time, so a stale table only costs a few characters, never breaks.
 *
 * Run after a data refresh to let new creatures/plushies/traits benefit from
 * compaction:  npx tsx scripts/gen_share_vocabulary.ts
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const VOCAB_FILE = path.join(ROOT, "src", "shared", "shareVocabulary.ts");

function readJson(rel: string): unknown {
  return JSON.parse(fs.readFileSync(path.join(ROOT, rel), "utf-8"));
}

function discoverNames(): string[] {
  const out: string[] = [];
  const push = (n: unknown) => {
    if (typeof n === "string" && n.trim().length > 0) out.push(n);
  };

  const creatures = (readJson("data/creatures.runtime.json") as { creatures?: Record<string, unknown>[] }).creatures ?? [];
  for (const c of creatures) {
    push(c.name);
    for (const key of ["passiveAbilities", "activatedAbilities", "breathAbilities"]) {
      const list = c[key];
      if (Array.isArray(list)) {
        for (const a of list) push(typeof a === "string" ? a : (a as { name?: unknown })?.name);
      }
    }
  }

  const plushies = (readJson("data/plushies.runtime.json") as { plushies?: { name?: unknown }[] }).plushies ?? [];
  for (const p of plushies) push(p.name);

  const traitsDoc = readJson("data/traits.runtime.json") as { traits?: { name?: unknown }[] };
  for (const t of traitsDoc.traits ?? []) push(t.name);

  const statusDoc = readJson("data/status_effects.runtime.json");
  const statuses = Array.isArray(statusDoc) ? statusDoc : Object.values(statusDoc as Record<string, unknown>);
  for (const s of statuses) push(typeof s === "string" ? s : (s as { name?: unknown })?.name);

  for (const k of Object.keys(readJson("data/special_abilities.runtime.json") as Record<string, unknown>)) push(k);

  // Dedup, preserve first-seen order.
  const seen = new Set<string>();
  const uniq: string[] = [];
  for (const n of out) {
    if (!seen.has(n)) {
      seen.add(n);
      uniq.push(n);
    }
  }
  return uniq;
}

function readExistingVocab(): string[] {
  if (!fs.existsSync(VOCAB_FILE)) return [];
  const src = fs.readFileSync(VOCAB_FILE, "utf-8");
  const start = src.indexOf("[");
  const end = src.lastIndexOf("]");
  if (start === -1 || end === -1 || end <= start) return [];
  const body = src.slice(start + 1, end);
  return [...body.matchAll(/"((?:[^"\\]|\\.)*)"/g)].map((m) => JSON.parse(`"${m[1]}"`) as string);
}

const existing = readExistingVocab();
const existingSet = new Set(existing);
const appended = discoverNames().filter((n) => !existingSet.has(n));
const vocab = [...existing, ...appended];

const body = vocab.map((n) => `  ${JSON.stringify(n)},`).join("\n");
const file = `// AUTO-GENERATED by scripts/gen_share_vocabulary.ts - do not edit by hand.
//
// APPEND-ONLY name table for COSM3 share links. A link stores a name as its
// index in this array, so existing entries must NEVER be reordered or
// removed - that would make old links resolve to the wrong name. Regenerating
// only appends new names at the end. Names not present here are stored inline
// at encode time, so a stale table only lengthens new links, never breaks one.
export const SHARE_VOCABULARY: readonly string[] = [
${body}
];
`;
fs.writeFileSync(VOCAB_FILE, file, "utf-8");
console.log(`Wrote ${vocab.length} names (${appended.length} new) to ${path.relative(ROOT, VOCAB_FILE)}`);
