// TS → Rust codegen for the effect registry.
//
// Reads STATUS_CATALOG (assembled from NAME_TO_EFFECT_META in
// src/engine/statusCatalog.ts) and emits a strongly-typed Rust module
// at wasm-engine/src/effects_registry.rs.
//
// Run: `npm run gen:registry` (or `npx tsx scripts/gen_effects_registry.ts`)
// after editing NAME_TO_EFFECT_META. The generated file is committed
// to the repo so CI does not need to run the codegen step.
//
// Output style: match arms keyed on the engine status id (e.g.
// "Bleed_Status"), returning Option<T> for fields the engine wants to
// branch on. Statuses not in the catalog return None - callers fall
// back to the legacy hand-written behaviour for the handful of Rust-
// only statuses (Aftershock, Ashy_Lungs, Paralyze_Status, etc.) that
// don't yet have a Reference entry.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { STATUS_CATALOG, type EffectShape } from "../src/engine/statusCatalog";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, "..");
const OUT_PATH = path.join(REPO_ROOT, "wasm-engine", "src", "effects_registry.rs");

const HEADER = `//! AUTO-GENERATED by scripts/gen_effects_registry.ts - DO NOT EDIT BY HAND.
//!
//! Source of truth: src/engine/statusCatalog.ts NAME_TO_EFFECT_META.
//! Regenerate with \`npm run gen:registry\` after editing the catalog.
//!
//! Effects in this registry are the ones that have a Reference entry
//! plus a NAME_TO_EFFECT_META row. Engine-only statuses (e.g.
//! Aftershock, Ashy_Lungs, Paralyze_Status) intentionally return None
//! here - the legacy hand-written paths in statuses.rs cover them.

#![allow(dead_code)]

#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum Polarity {
    Positive,
    Negative,
    Neutral,
}

#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum Category {
    RegenBuff,
    StatBuff,
    StatDebuff,
    DotDamage,
    TickHeal,
    Control,
    AilmentMeta,
    NeutralMarker,
}

#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum StackRule {
    Stacking,
    NonStacking,
    Unique,
}
`;

const POLARITY_RUST: Record<string, string> = {
  positive: "Polarity::Positive",
  negative: "Polarity::Negative",
  neutral: "Polarity::Neutral",
};

const CATEGORY_RUST: Record<string, string> = {
  regen_buff: "Category::RegenBuff",
  stat_buff: "Category::StatBuff",
  stat_debuff: "Category::StatDebuff",
  dot_damage: "Category::DotDamage",
  tick_heal: "Category::TickHeal",
  control: "Category::Control",
  ailment_meta: "Category::AilmentMeta",
  neutral_marker: "Category::NeutralMarker",
};

const STACK_RULE_RUST: Record<string, string> = {
  stacking: "StackRule::Stacking",
  non_stacking: "StackRule::NonStacking",
  unique: "StackRule::Unique",
};

function f64Literal(value: number): string {
  // Plain integer doubles get an explicit decimal so rustfmt keeps them as f64.
  if (Number.isInteger(value)) return `${value}.0_f64`;
  return `${value}_f64`;
}

// Pull the percentage-point modifier for a given stat + opStyle out
// of an EffectShape. Recurses into `composite` parts so a status that
// pairs (say) regen reduction with a meta-marker still surfaces the
// modifier here. Returns null when no `stat_modifier` part matches.
function extractStatModifierPct(
  effect: EffectShape,
  statKey: string,
  opStyle: "add_pct" | "per_stack_pct",
): number | null {
  if (effect.kind === "stat_modifier" && effect.opStyle === opStyle) {
    const value = effect.mods[statKey];
    if (typeof value === "number") return value;
  }
  if (effect.kind === "composite") {
    for (const part of effect.parts) {
      const inner = extractStatModifierPct(part, statKey, opStyle);
      if (inner !== null) return inner;
    }
  }
  return null;
}

function emitMatch<T>(
  fnName: string,
  returnType: string,
  pick: (entry: (typeof STATUS_CATALOG)[number]) => T | null | undefined,
  format: (value: T) => string,
): string {
  const arms: string[] = [];
  for (const entry of STATUS_CATALOG) {
    const value = pick(entry);
    if (value === null || value === undefined) continue;
    arms.push(`        ${JSON.stringify(entry.id)} => Some(${format(value)}),`);
  }
  return [
    `pub fn ${fnName}(status_id: &str) -> Option<${returnType}> {`,
    `    match status_id {`,
    ...arms,
    `        _ => None,`,
    `    }`,
    `}`,
  ].join("\n");
}

// Pure function form - exported so the drift CI gate (vitest) can
// re-run the codegen logic and compare against the committed
// effects_registry.rs file.
export function generateRegistryRustSource(): string {
  const fns: string[] = [];

  fns.push(
    emitMatch(
      "polarity",
      "Polarity",
      (e) => e.polarity,
      (v) => POLARITY_RUST[v],
    ),
  );

  fns.push(
    emitMatch(
      "category",
      "Category",
      (e) => e.category,
      (v) => CATEGORY_RUST[v],
    ),
  );

  fns.push(
    emitMatch(
      "stack_rule",
      "StackRule",
      (e) => e.stackRule,
      (v) => STACK_RULE_RUST[v],
    ),
  );

  fns.push(
    emitMatch(
      "default_duration_sec",
      "f64",
      (e) => e.defaultDurationSec,
      (v) => f64Literal(v),
    ),
  );

  fns.push(
    emitMatch(
      "default_tick_sec",
      "f64",
      (e) => e.defaultTickSec,
      (v) => f64Literal(v),
    ),
  );

  fns.push(
    emitMatch(
      "default_max_stacks",
      "f64",
      (e) => e.defaultMaxStacks,
      (v) => f64Literal(v),
    ),
  );

  // Flat percentage-point modifier on health regen (add_pct).
  // Examples: Muddy +25, Clean Water +20, Refreshed +5, Bad Omen -25,
  // Bleed -100 (full block). hp_regen_multiplier_from_statuses
  // multiplies by (1 + pct / 100).
  fns.push(
    emitMatch(
      "regen_modifier_pct",
      "f64",
      (e) => extractStatModifierPct(e.effect, "healthRegenPct", "add_pct"),
      (v) => f64Literal(v),
    ),
  );

  // Per-stack percentage-point modifier on health regen
  // (per_stack_pct). Examples: Burn -10 per stack, Disease -15 per
  // stack. hp_regen_multiplier_from_statuses multiplies by
  // max(0, 1 + pct * stacks / 100).
  fns.push(
    emitMatch(
      "regen_modifier_per_stack_pct",
      "f64",
      (e) => extractStatModifierPct(e.effect, "healthRegenPct", "per_stack_pct"),
      (v) => f64Literal(v),
    ),
  );

  // Convenience boolean: known to the registry (i.e. has a Reference
  // entry + NAME_TO_EFFECT_META row).
  fns.push(
    [
      `pub fn is_known(status_id: &str) -> bool {`,
      `    polarity(status_id).is_some()`,
      `}`,
    ].join("\n"),
  );

  const body = fns.join("\n\n");
  return `${HEADER}\n${body}\n`;
}

export const REGISTRY_OUT_PATH = OUT_PATH;

// Only run the file-writing side-effect when invoked directly via the
// CLI, not when imported from the drift test.
const invokedDirectly =
  import.meta.url === `file://${process.argv[1]?.replace(/\\/g, "/")}`
  || import.meta.url.endsWith(process.argv[1]?.replace(/\\/g, "/") ?? "");

if (invokedDirectly) {
  fs.writeFileSync(OUT_PATH, generateRegistryRustSource(), "utf8");
  console.log(
    `Generated ${path.relative(REPO_ROOT, OUT_PATH)} - ${STATUS_CATALOG.length} entries.`,
  );
}
